### DISCUSSION TITLE
Warn about missing "roles:"

### DISCUSSION THREAD

**Discussion by matkoniecz** [ansible/ansible-lint#1072] [Q&A] [answered]
##### Summary
Warn where "roles" is missing and as result no action would be taken.

(maybe there is a good reason to have something like that? in that case - sorry)

##### Issue Type

- Feature Idea

##### Additional Information
An actual example from something that triggered my attempt to find an Ansible linter:

```
- name: final_cleanup
  hosts: all
  vars:
    - username_of_a_local_user: mateusz
  become: yes
    - apt_packages_autoremove_unneded
    - apt_packages_upgrade
```
