### DISCUSSION TITLE
ansible-lint 5.0 upgrade guidelines

### DISCUSSION THREAD

**Discussion by ssbarnea** [ansible/ansible-lint#1150] [Show and tell] [answered]
This post aims to document what changes you should expect when **upgrading ansible-lint to 5.0**.

# Assure you install the linter correctly
* Read updated [installation instructions](https://ansible-lint.readthedocs.io/en/latest/installing.html#using-pip). You will have to manually specify which version of ansible you want to be used as none will be installed implicitly. Same applies for yamllint, which is a new extra.
* You will likely have to do `git ignore .cache` as linter may create a cache folder in multiple situations: standalone roles, mocking and requirements installation are all using it.
* If you are running ansible-lint as a pre-commit hook, update the configuration like below:

```yaml
#  .pre-commit-config.yaml
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.0.0
    hooks:
      - id: ansible-lint
        # add lines below:
        additional_dependencies:
          - ansible>=2.10,<2.11  # or use ansible-base if you want the slim version
          - yamllint>=1.25.0,<2.0. # this enables YAML support
```

# If you have custom rules you will have to update them as base class methods changed.
* `Rule.match()` signatured changed by #1153
* `Rule.matchtask()` signature changed by #1247
* `Rule.matchyaml()` signature changed by #955 

# Other notable changes
* You need to install yamllint package yourself to activate this rule as this is not listed as a direct dependency.
* removed rules [E201](https://ansible-lint.readthedocs.io/en/latest/default_rules.html#trailing-whitespace) and [E204](https://ansible-lint.readthedocs.io/en/latest/default_rules.html#lines-should-be-no-longer-than-160-chars) that are already covered by yamllint were removed.  We now use yamllint to perform style checks.  If you skipped these rules you now need to use their new tags: `yamllint-trailing-spaces` instead of `201` and  `yamllint-trailing-spaces` instead of `204`

# Known bugs or limitations
* if you do not want to get yamllint errors reported but you already have yamllint module installed, you need to add `yaml` to the `skip_list`.

**Comment by MarkusTeufelberger** [comment, marked as answer]
Is it really necessary to install `ansible` or is `ansible-base` (soon `ansible-core`) already enough?

I also recommend to pin versions a bit tighter than just "whatever is newest".

**Reply by ssbarnea** [reply]
@MarkusTeufelberger I updated the example to mention that ansible-base can be used. The installation instructions already do that. 

Shortly: the linter works fine with the base/core version of Ansible and it will also raise errors if user is trying to use missing community collections.

I know that this made installation bit more complex, but it was the only way possible to empower the users to pick their own poison.

I also included some safe ranges in the examples, ones that should avoid surprises from major releases.

**Comment by sean-m-sullivan** [comment]
Been testing this today, with two collections, both had their issues in previous versions of 5.0. This is how I've set it to run. 
```
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v5.0.0rc1
    hooks:
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: >-
          ansible-lint -vp -c .github/workflow-config/.ansiblelint.yml
```
and this is the config
```
parseable: true
use_default_rules: true
```

Everything is looking good from the testing.
