### DISCUSSION TITLE
Should git-latest trigger when `update: false`?

### DISCUSSION THREAD

**Discussion by Jackenmen** [ansible/ansible-lint#1817] [Ideas]
Right now, git-latest triggers for a task configuration like this:
```yaml
- name: Clone ansible-lint.
  ansible.builtin.git:
    repo: https://github.com/ansible-community/ansible-lint
    dest: "{{ ansible_user_dir }}/work/ansible-lint"
    update: false
```

I'm wondering, is this an intentional choice? Without an explicit `version`, this will still properly report "ok" status if the repository is already cloned so requiring a version here seems unnecessary.
I'm using Ansible to provision my workstation so I was trying to use the git module to clone repositories I plan to work on and as such, I always want to clone an up-to-date repository.

I can use `# noqa` on specific rules of course so this isn't a big problem, I'm just wondering if this rule intentionally includes tasks with `update: false` or if it's just an oversight.
