### DISCUSSION TITLE
Disallow old syntax

### DISCUSSION THREAD

**Discussion by gtirloni** [ansible/ansible-lint#2188] [New rules] [answered]
It would be nice if we had a rule that would disallow this syntax:

```
- name: OpenSSH daemon configuration
  become: yes
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: reload-sshd
```

I don't think the syntax is deprecated by Ansible but it's been years since the YAML format is the preferred way:

```yaml
- name: OpenSSH daemon configuration
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: reload-sshd
```

I ran it through ansible-lint 6.2.2 and it did not complain about the syntax. Also checking the rules directory didn't show anything related.
