### DISCUSSION TITLE
How do you like to format long Jinja strings?

### DISCUSSION THREAD

**Discussion by cognifloyd** [ansible/ansible-lint#2255] [General]
In order to finish https://github.com/ansible/ansible-lint/pull/2066, I need to determine how we should format long Jinja strings.

Think of tools like [`black`](https://black.readthedocs.io/en/stable/) and [`prettier`](https://prettier.io/) which do opinionated reformatting. With that in mind please answer these questions and provide examples:

- How do you format long Jinja strings in playbooks, tasks files, and vars files?
- In particular: If you have to add line breaks to keep lines within a certain length, where do you add those line breaks?

**Comment by cognifloyd** [comment]
Here are examples that adds a line break after `|` (filter pipe): https://stackoverflow.com/a/56865320/1134951
```yaml
    - set_fact:
        za_ver: "{{ ansible_facts.packages['zabbix-agent']|
                    map(attribute='version')|
                    list }}"
      when: "'zabbix-agent' in ansible_facts.packages"

    - set_fact:
        za_ver: "{{ ansible_facts.packages['zabbix-agent']|
                    json_query('[].version') }}"
      when: "'zabbix-agent' in ansible_facts.packages"
```
