### DISCUSSION TITLE
key-order for task tags before or after when?

### DISCUSSION THREAD

**Discussion by ssbarnea** [ansible/ansible-lint#2520] [Polls]
We need to decide if `tags` should be **before or after** `when` in the key-order used for tasks.

To give you a better idea, I will include two examples that also include all the [currently ordered keys](https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/rules/key_order.py#L16), with block/rescue/always which was already established to remain at the bottom.

```yaml
# tags after when
- name: ...
  ...
  when: ...
  tags: ...
  block: ...
  rescue: ...
  always: ...
```

```yaml
# tags before when
- name: ...
  ...
  tags: ...
  when: ...
  block: ...
  rescue: ...
  always: ...
```
