### DISCUSSION TITLE
Allow scoping of rules to Ansible module types

### DISCUSSION THREAD

**Discussion by PayBas** [ansible/ansible-lint#2599] [Ideas]
Allowing rules to be scoped to specific Ansible module types allows for more granular control over the linting process.

Prime example for me is:
```yaml
tasks:
  - meta: flush_handlers
```
Which results in:
```
name[missing]: All tasks should be named. (warning)
```

Now both disabling `skip_list: - name[missing]` and `# noqa name[missing]` are not suitable for me. The granularity is either way too big, or too small.

How about an intermediary scope feature for the `.ansible-lint` config:
```yaml
skip_list[ansible.builtin.meta]:
  - name[missing]

# or

module_type_rules:
  - module: ansible.builtin.meta
    warn_list:
      - fqcn[action-core]
    skip_list:
      - name[missing]
```
Module-type scoped rules would take precedence over globally scoped rules obviously, but would still be superseded by `# noqa`

Related:
https://github.com/ansible/ansible-lint/issues/364
https://github.com/ansible/ansible-lint/issues/2111
https://github.com/ansible/ansible-lint/discussions/773
