### DISCUSSION TITLE
Is there any way to change yamllint options?

### DISCUSSION THREAD

**Discussion by robin-wayve** [ansible/ansible-lint#2612] [Q&A] [answered]
For example, if I wanted to use `indent-sequences: false` since that's how the yaml spec presents sequences https://yaml.org/spec/1.2.2/#21-collections

**Comment by apatard** [comment, marked as answer]
afaik, it's possible to put a .yamllint file inside the project root directory and ansible-lint will use it.

Example of .yamllint:

```
---
extends: default

rules:
  indentation:
    indent-sequences: false
```
