### DISCUSSION TITLE
sequential task considered to be called in handlers

### DISCUSSION THREAD

**Discussion by elafontaine** [ansible/ansible-lint#273] [Ideas]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible 2.3.1.0
ansible-lint 3.4.13
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

When task need to be executed sequentially (they depend on the result of the previous task), we should be able to ignore a specific warning ("task should probably be a handler" in this case).
 ```
 - name: mount disk if not present
   mount: 
       dev: {{ dev_path }}
   register : output
 - name: format disk if not in the right format
   fs:
      type: xfs
      label: {{ partition_name }}
   when: output.result == changed
   tag:
     - skip_ansible_lint: {{ lint_rule_number }}

```

# Actual Behaviour 

If we want to remove the warning, we need to remove everything from that task:
 ```
 - name: mount disk if not present
   mount: 
       dev: {{ dev_path }}
   register : output
 - name: format disk if not in the right format
   fs:
      type: xfs
      label: {{ partition_name }}
   when: output.result == changed
   tag:
     - skip_ansible_lint
```
