### DISCUSSION TITLE
Allow yamllint warnings to come through as ansible-lint warnings

### DISCUSSION THREAD

**Discussion by jwilliams-shadowsoft** [ansible/ansible-lint#2884] [Ideas]
Although `yamllint` can be configured to generate warnings for specific rule violations, this return does not seem to be passed back up to `ansible-lint`. 

For instance, assuming I don't want to have multiple spaces after a colon be an error, I could (in the `yamllint` config):
```
rules:
  colons:
    level: warning
```
But there does not seem to be a way to represent this in the `ansible-lint` config file. You can only make all yaml rule violations warnings or skips.

Other options added to the `yamllint` file seem to work fine, like "disable" or setting the "truthy" values:
```
rules:
  colons: disable
  truthy:
    allowed-values:
    - "yes"
    - "no"
    - "true"
    - "false"
```
Just opting for the most configurability we can get here.
