### DISCUSSION TITLE
Warn about short key IDs when using ansible.builtin.apt_key module

### DISCUSSION THREAD

**Discussion by sugar700** [ansible/ansible-lint#2947] [New rules]
ansible-lint should warn when using 32-bit key IDs (8 characters) in apt_key module as they are insecure due to their length (https://evil32.com/). For example:

```yaml
- name: Add an Apt signing key, will not download if present
  ansible.builtin.apt_key:
    id: 473041FA
    url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
    state: present
```

This can be written as follows:
```yaml
- name: Add an Apt signing key, will not download if present
  ansible.builtin.apt_key:
    id: 9FED2BCBDCD29CDF762678CBAED4B06F473041FA
    url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
    state: present
```

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html recommends against this practice: "Use full fingerprint (40 characters) key ids to avoid key collisions."
