### DISCUSSION TITLE
Some ansible lint rule are not checked for the playbook

### DISCUSSION THREAD

**Discussion by aseefahmed** [ansible/ansible-lint#2966] [Q&A]
name[missing] rule is not checked for the standalone playbook. however, its checked for the role though. here is an example ansible-playbook I tested and once I run ansible-lint, it says 'Passed with production profile: 0 failure(s), 0 warning(s) on 1 files' which means no error/warning found:

```
---
- name: Update web servers
  hosts: webservers
  remote_user: root
  gather_facts: false

  tasks:
    - ansible.builtin.yum:
        name: httpd
        state: latest
    - ansible.builtin.template:
        src: /srv/httpd.j2
        dest: /etc/httpd.conf
```
