### DISCUSSION TITLE
Rule to enforce idempotency of tasks

### DISCUSSION THREAD

**Discussion by nre-ableton** [ansible/ansible-lint#3058] [New rules] [answered]
ansible-lint already has `no-changed-when`, which until #3050 could be used to enforce that tasks such as `command`/`shell` did not execute unnecessarily. The message that `no-changed-when` emits even says "Commands should not change things if nothing needs doing." This is correct, but unfortunately `no-changed-when` is only taking care of half of the job here.

Confusion over the use of `no-changed-when` resulted in #3050 (see also https://github.com/ansible/ansible-lint/issues/2629), which clarified that this rule should enforce that tasks such as `command`/`shell` (and others) always report an accurate `changed` state. However, ansible-lint should have another rule that also enforces idempotency for such tasks.

For example, here's a problematic task that sets the system hostname on Ubuntu systems:

```yaml
- name: Set hostname
  become: true
  ansible.builtin.command: "hostnamectl set-hostname {{ system_hostname }}"
  changed_when: true
```

By adding `changed_when: true`, it satisfies `no-changed-when` but this task on its own is not great because it always modifies the system state. The best practice _should_ be something like this:

```yaml
- name: Get hostname
  ansible.builtin.command: "hostname"
  changed_when: false
  register: hostname

- name: Set hostname
  become: true
  ansible.builtin.command: "hostnamectl set-hostname {{ system_hostname }}"
  when: hostname.stdout != system_hostname
```

This is a trivial example, but there are plenty of cases where one wants to avoid running a potentially large and system-changing operations if they aren't necessary. As `command`/`shell` are the primary culprits for such cases (since nearly all built-in tasks are idempotent), I would recommend calling the rule `idempotent-command` or something along those lines.
