### DISCUSSION TITLE
Why does my tasks file (under tasks/do_sth/do_sth.yaml) say "block is a required property"?

### DISCUSSION THREAD

**Discussion by blv-brunoneyra** [ansible/ansible-lint#3304] [Q&A] [answered]
File looks like this:

```yaml
- hosts: all
  become: true

  tasks:
    - name: Clean logs
      ansible.builtin.file:
        state: absent
        path: "/var/log/myproj.log"
```

and it says:

```
'block' is a required property [schema[tasks]]
```
