### DISCUSSION TITLE
ansible-lint failing      1 schema[playbook] basic   core

### DISCUSSION THREAD

**Discussion by jpatallah** [ansible/ansible-lint#3426] [Q&A]
versions:
ansible-lint 6.16.0

My playbook has the following format:
```
---
- name: <description>
  hosts: all

  vars_files:
    - group_vars/file1.yml
    - group_vars/file2.yml
    - group_vars/file3.yml
    - group_vars/file4.yml
    - group_vars/file5.yml
    - group_vars/file6.yml

  vars:
    - ansible_connection: ssh
    - ansible_shell_type: powershell

  roles:
    - role: <role_name>
 ```

I am getting the following error
```
schema[playbook]: ...is not valid under any of the given schemas
site.yml:1  Returned errors will not include exact line numbers, but they will mention
the schema name being used as a tag, like ``schema[playbook]``,
```

any help would be appreciated
