### DISCUSSION TITLE
False Positive on: 'command-instead-of-module' - "tar used in place of unarchive module"

### DISCUSSION THREAD

**Discussion by mdebord-dlr** [ansible/ansible-lint#3488] [General]
Take this use-case of extracting an archive to some local temp staging directory (before interacting with any remotes)... 

```
- name: "Extract archive in local dir for install prep"  
  command:
    cmd: "tar -xzf foo.tar.gz"
    chdir: "{{ playbook_dir }}/../build/"
  delegate_to: localhost
  run_once: true
  vars:
    ansible_connection: local
```

The **"unarchive"** module is not applicable here because it extracts to the remote machine(s).

In this case the use of the tar command is valid, so it doesn't seem like it should be failing during any tests/lints. However, ansible-lint will flag it with a "command-instead-of-module" failure.
