### DISCUSSION TITLE
Clarity on when: positioning

### DISCUSSION THREAD

**Discussion by dgibbs64** [ansible/ansible-lint#3532] [General]
I am looking at the key-order rule and noticed the when: is located at the top https://ansible-lint.readthedocs.io/rules/key-order/ in the example.

I wanted to clarify what Is the recommended position to put when? Is there an opinion on this? and if not should ansible-lint create an opinion on the positioning of when?
```
- name: "Install nano"
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name: nano
    state: latest
```
or
```
- name: "Install nano"
  ansible.builtin.dnf:
    name: nano
    state: latest
  when: ansible_os_family == "RedHat"
```
Thanks for any guidance

**Comment by briantist** [comment]
For tasks, I believe both of your answers would be acceptable. It's `block`, `rescue`, and `always` where this becomes problematic. Before I knew that this ordering was possible, I wrote a lot of stuff like this for example:

```yaml
- name: Named block
  block:
    - name: Task 1
      etc: ...

    - name: Task 2
      etc: ...

  # block
  when: condtion applied to block
```

The longer the block is, the harder it is to see that the `when` applies at the block level. With nested blocks, this becomes even worse.

I used to put the comment `# block` there (sometimes with a name if it's nested) to help this very issue.

But it's way clearer to rewrite it like this:

```yaml
- name: Named block
  when: condtion applied to block
  block:
    - name: Task 1
      etc: ...

    - name: Task 2
      etc: ...
```

---

So I'm very happy to see this rule, but [I'm still not happy that it was introduced in a minor version causing new failures but that's a separate discussion](https://github.com/ansible/ansible-lint/discussions/3183).
