### DISCUSSION TITLE
unarchive, remote_src and file urls as source

### DISCUSSION THREAD

**Discussion by laurentS** [ansible/ansible-lint#3595] [New rules]
I just had an error in my playbook with:

```yaml
- name: Install some CLI
  become: true
  ansible.builtin.unarchive:
    src: "https://someurl.com/filename.tar.gz"
    dest: /usr/local/bin/
    mode: "0755"
```
which failed because `remote_src: true` was missing, so the code looked for a file named as the url on the local filesystem.

I think that if `src` is a url, it's very likely the author actually wants to fetch a remote file, and the linter could raise a warning about it, suggesting to add the missing `remote_src` attribute. In theory, it could be a filename, but I think using such a filename would be asking for trouble anyway, so not really "best practice".

There are probably a few other commands which use `remote_src` or something similar that could be checked that way too.
