### DISCUSSION TITLE
github-actions: The vault password file was not found

### DISCUSSION THREAD

**Discussion by ReenigneArcher** [ansible/ansible-lint#3713] [General]
##### Summary

Ansible lint gives warnings/errors that it cannot find the vault password file. I create my vault password using the following step before the ansible lint step.

```yml
run: echo ${{ secrets.MYSECRET || '1234' }} > .vault-password
```

I run ansible lint with this step:

```yml
uses: ansible/ansible-lint@v6.18.0
with:
  args: "playbooks/"
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
```

6.18.0 (using ansible-lint as github action)

- ansible installation method: pypi
- ansible-lint installation method: using github action

##### STEPS TO REPRODUCE

Set password file location in config.

**ansible.cfg**
```ini
vault_password_file=.vault-password
```

Create vault passowrd file in workflow, as shown above.

Run ansible lint action, as shown above.

##### Desired Behavior

Find the file, that was created.

Possible security bugs should be reported via email to `security@ansible.com`

##### Actual Behavior

File was not found.

```txt
Warning: /some_playbook.yml:1 [WARNING]: Error getting vault password file (default): The vault password file /runner/_work/ansible-repo/ansible-repo/.vault-password was not found
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Additional Information**

I use the same method of creating the .vault-password file to actually run ansible playbooks inside of GitHub actions, and that works fine. I also did not have this problem on the now depreciated `ansible-lint-action` repository.

**Comment by mszumilak** [comment]
This seems to be a duplicate of https://github.com/ansible/ansible-lint/issues/2443

**Comment by ReenigneArcher** [comment]
@mszumilak Maybe similar but I don't think it's a duplicate. They are having jinja and variable issues. I am having the issue where it cannot find the vault password file that does exist.

**Comment by ssbarnea** [comment]
@ReenigneArcher I do think that the vault password is not found because the current directory is different when running from lint. I would recommend you to ensure that you configure the path to vault file to be a full path, just in case.

Print the full of your dumped file, to check it.

**Reply by ReenigneArcher** [reply]
Why would the working directory be different? I have not specified a different working directory.

And I don't think that's the case, otherwise ansible would not be able to find my `ansible.cfg` file which is in the working directory, and the only place where the vault password file is specified.

```yml
---
# Lint Ansible files.

name: Ansible lint

# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ansible_lint:
    name: ansible lint
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create vault_password
        run: |
          echo "1234" > .vault-password

      - name: Ansible lint
        id: ansible-lint
        uses: ansible/ansible-lint@v6.18.0
        with:
          args: "playbooks/"

      - name: Remove vault_password
        if: always()
        run: |
          rm -f .vault-password
```

Works fine with the old action, using.

```yml
      - name: Ansible lint
        id: ansible-lint
        uses: ansible/ansible-lint-action@v6.17.0
        with:
          path: "playbooks/"
```

Also added a statement to print the current directory and contents right before the ansible lint action.

```bash
  echo "1234" > .vault-password
  echo "Current working directory: $(pwd)"
  echo "Current directory contents:"
  ls -a .
```

As you can see the file does exist.

```txt
Current working directory: /runner/_work/ansible-repo/ansible-repo
Current directory contents:
.
..
.git
.github
.gitignore
.vault-password
.yamllint.yml
README.md
ansible.cfg
inventory
playbooks
requirements.txt
requirements.yml
```

So, yea. This is definitely a bug in this action, since it can't find a file that does exist.


```txt
Warning: /some_playbook.yml:1 [WARNING]: Error getting vault password file (default): The vault password file /runner/_work/ansible-repo/ansible-repo/.vault-password was not found
```

**Reply by ReenigneArcher** [reply]
Bump

**Reply by ReenigneArcher** [reply]
FYI:

Works fine if I replace the GitHub action with CLI version.

```yml
      - name: Ansible lint
        run: |
          ansible-lint ./playbooks
```
