### DISCUSSION TITLE
var-naming[no-jinja] - why templating variable names is bad?

### DISCUSSION THREAD

**Discussion by Orlik3000** [ansible/ansible-lint#3794] [Q&A]
Hello, 

Such a basic example task, with variable name templating:

```yaml
- name: Templating var
  ansible.builtin.set_fact:
    "prefix_{{ variable1 }}_sufix": "{{ variable2 }}"
  vars:
    variable1: "foo"
    variable2: "bar"
```
... works fine, but ansible-lint (as expected to current rules) returns:
```
var-naming[no-jinja]: Variables names must not contain jinja2 templating.
```
But I cannot find any information why this is actually a bad practice? Could you please explain?

I've only found only a single thing in this topic which is ansible-lint issue (relatively old as from 2021) https://github.com/ansible/ansible-lint/issues/1680 , where it seems like templating variables was acceptable at that point of time.
Additionally, ansible-lint finds this violation only when used in playbook, while the same task defined in role is not flagged.

Thanks in advance.
