### DISCUSSION TITLE
Why is this task marked as bad indentation.

### DISCUSSION THREAD

**Discussion by janorn** [ansible/ansible-lint#3895] [General]
Why does this code snippet from ansible [commands example](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#examples) get marked as
`wrong indentation: expected 6 but found 8`
I have the following settings in .yamllint
`indent-sequences: consistent`
```
- name: Use 'argv' to send a command as a list - leave 'command' empty
  ansible.builtin.command:
    argv:
      - /usr/bin/make_database.sh
      - Username with whitespace
      - dbname with whitespace
    creates: /path/to/database
```
