### DISCUSSION TITLE
Allow exact selection of enabled rules (custom profiles?)

### DISCUSSION THREAD

**Discussion by Jackenmen** [ansible/ansible-lint#3953] [Ideas]
Maybe I'm missing something but I couldn't find a way to select the exact ruleset that I want to use:
- using `--profile` means that anything passed with `--enable-list` that isn't already in the profile won't be enabled (which I only found out by using doubly verbose `-vv` flag)
- using `--enable-list` *without* a `--profile` means that all rules that aren't opt-in will be enabled
- using `--tags` works *only if* you can find some set of tags that have exactly the rules that you want

All other options are for disabling rules which isn't particularly helpful when I'm hoping to opt into rules, not opt out of them.

**Comment by nantiferov** [comment]
Also noticed same problem. Interesting that[ in original issue was a discussion](https://github.com/ansible/ansible-lint/issues/2109#issuecomment-1130044955) to provide ability to create custom profiles, but looks like wasn't implemented unfortunately.

I went through [list of rules for existing profiles](https://github.com/ssbarnea/ansible-lint/blob/main/src/ansiblelint/data/profiles.yml) and combined this config with ones that makes sense to me. 

Might be useful to someone:

```yaml
---
offline: true # Disables installation of requirements.yaml and schema refreshing

# Based on https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/data/profiles.yml
# List of all rules https://ansible.readthedocs.io/projects/lint/rules/
tags:
  # min profile
  - internal-error
  - load-failure
  - parser-error
  - syntax-check
  # basic profile
  - command-instead-of-module
  - command-instead-of-shell
  - deprecated-bare-vars
  - deprecated-local-action
  - deprecated-module
  - inline-env-var
  - literal-compare
  - jinja
  - jinja[invalid] # both jinja required
  - no-free-form
  - no-jinja-when
  - no-tabs
  - partial-become
  - playbook-extension
  - role-name
  - schema
  - name
  - name[missing] # both name required
  - var-naming
  - var-naming[pattern] # both var-naming required
  - yaml
  # safety
  - package-latest
  - risky-octal
  - risky-shell-pipe
  # production
  - fqcn
  - fqcn[action-core] # both fqcn required

# ansible-lint doesn't automatically load rules that have the 'opt-in' tag
enable_list:
  - yaml # Force yamllint to be installed
```

If some subset of enabled rules should be disabled, use skip_list, like

```yaml
skip_list:
  - name[template]
```
