### DISCUSSION TITLE
ignore name[missing] rule in 1 file

### DISCUSSION THREAD

**Discussion by janw-me** [ansible/ansible-lint#3985] [Q&A]
I have the following file:
```yml
---
- name: Configure all things php
  tags: php
  block:
    # yamllint disable
    - ansible.builtin.import_tasks: includes/php.yml
    - ansible.builtin.import_tasks: includes/composer.yml
    - ansible.builtin.import_tasks: includes/wp-cli.yml
    # yamllint enable
```

This gives three _name[missing]: All tasks should be named._ And I get that.
But I just want to ignore the error here, while keeping it in other instances.
The default `# yamllint` doesn't seem to work.

How do I exclude this?
