### DISCUSSION TITLE
jmespath dependency

### DISCUSSION THREAD

**Discussion by AirOnSkin** [ansible/ansible-lint#4321] [General] [answered]
Hello ansible-lint community

I'm struggling with switching from the old linter (`ansible-community/ansible-lint-action`) to this one because of a missing dependency: `jmespath`

Linting produces the following error multiple times:
```
jinja[invalid]: You need to install "jmespath" prior to running json_query filter
roles/some_project/tasks/some_file.yml:16 Task/Handler: Filter some json payload

Error: You need to install "jmespath" prior to running json_query filter
```

I see `jmespath` is present in https://github.com/ansible/ansible-lint/blob/main/.config/constraints.txt#L45, but not in https://github.com/ansible/ansible-lint/blob/main/.config/requirements-lock.txt

What's the best practice to add this additional dependency to our linting workflow?

Cheers,
Stefan

**Comment by konstruktoid** [comment]
Have you tried something similiar to this?

```yaml
      - name: Install system dependencies
        run: |
          sudo apt-get --assume-yes install python3-pip --no-install-recommends
          python3 -m pip install --user -U jmespath
```

**Reply by AirOnSkin** [reply]
I did try to setup python myself and install the dependency along with the others from the requirements file, albeit in a slightly different way. With that approach the package was not available at runtime and I got the same message. I also just tested what you've posted and get the same situation:
![Screenshot 2024-09-10 at 13 55 53](https://github.com/user-attachments/assets/bb0527c2-e85f-4dae-93f1-963d3d244c72)
The package is installed as a separate step before ansible-lint runs. But the ansible-lint action has its own [setup of python and dependencies](https://github.com/ansible/ansible-lint/blob/main/action.yml#L43-L69) ... so I'm thinking that just installing `jmespath` like you suggested isn't correct in this situation ...

**Reply by konstruktoid** [reply]
This is how I use it https://github.com/konstruktoid/ansible-role-hardening/blob/master/.github/workflows/molecule.yml

If `jmespath` isn't installed:

```sh
$ ansible-lint
WARNING  Listing 3 violation(s) that are fatal
jinja[invalid]: You need to install "jmespath" prior to running json_query filter
tests/debug_facts.yml:58 Task/Handler: Get DSA keys

jinja[invalid]: You need to install "jmespath" prior to running json_query filter
tests/debug_facts.yml:65 Task/Handler: Get short RSA keys

jinja[invalid]: You need to install "jmespath" prior to running json_query filter
tests/debug_facts.yml:72 Task/Handler: Get owner of old keys

Read documentation for instructions on how to ignore specific rule violations.

              Rule Violation Summary
 count tag            profile rule associated tags
     3 jinja[invalid] basic   formatting

Failed: 3 failure(s), 0 warning(s) on 147 files. Profile 'production' was required, but 'min' profile passed
```

**Reply by AirOnSkin** [reply]
I see. You're not using the [ansible-lint GH action](https://github.com/marketplace/actions/run-ansible-lint) but instead just the binary from pip 🤔

**Reply by konstruktoid** [reply]
I actually do, I run multiple versions: https://github.com/konstruktoid/ansible-role-hardening/tree/master/.github/workflows


From https://github.com/konstruktoid/ansible-role-hardening/actions/runs/10782079743/job/29901378202#step:6:17
"WARNING  The following filters were mocked during the run: json_query"

**Reply by AirOnSkin** [reply, marked as answer]
Sorry for the late reply, I was on holidays.

In the end I got it to work with setting up all the packages myself and ignoring the provided ansible-lint GH action:

```yaml
---
name: Ansible Lint
on:
  # not using 'push' because of the if-condition below
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python3-pip
          pip install ansible ansible-lint boto3 jmespath

      - name: Run ansible-lint
        run: |
          cd "${{ github.workspace }}/aws" || exit 1
          ansible-lint -c ../.config/ansible-lint.yml || exit 1
```
