### DISCUSSION TITLE
schema[playbook]: $[1].roles[0] 'role' is a required property

### DISCUSSION THREAD

**Discussion by khalangy** [ansible/ansible-lint#4327] [Q&A] [answered]
Hello,
I have playbooks in a folder named plays
In my ansible.cfg I have `playbook_dir = ./plays`

Playbook example : 
```yml
---
- name: "Test | test"
  hosts: "bdd"
  become: true
  gather_facts: true
  roles:
    - name: mariadb
      tags: mariadb
```

I have this error whan I ran ansible-lint : 
```
schema[playbook]: $[0].roles[0] 'role' is a required property. See https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#roles
plays/test.yml:1  Returned errors will not include exact line numbers, but they will mention
the schema name being used as a tag, like ``schema[playbook]``,
``schema[tasks]``.

This rule is not skippable and stops further processing of the file.

If incorrect schema was picked, you might want to either:

* move the file to standard location, so its file is detected correctly.
* use ``kinds:`` option in linter config to help it pick correct file type.
```

I tried to add this in my .ansible-lint file but the error is still present :disappointed: 
```
---
kinds:
  - playbook: "**/plays/*.{yml,yaml}"
```

Is someone can help me with this error please ? 

Bast regards

**Comment by khalangy** [comment, marked as answer]
Ok my bad I found ! 
I have to put role insted of name ! 
```yml
---
- name: "Test | test"
  hosts: "bdd"
  become: true
  gather_facts: true
  roles:
    - role: mariadb
      tags: mariadb
```
