### DISCUSSION TITLE
Help needed 🙏! Using ansiblelint/schemas/ansible.json to validate task role

### DISCUSSION THREAD

**Discussion by SquirrelDeveloper** [ansible/ansible-lint#4389] [Q&A]
Hi everyone,

I just spent several hours without success to use ansible.json to validate my roles.
I have the following directory:
```
/agent/
/agent/install.yml
/agent/roles/
/agent/roles/install_agent_docker/
/agent/roles/install_agent_docker/tasks/
/agent/roles/install_agent_docker/tasks/main.yml
/agent/roles/install_agent_node/
/agent/roles/install_agent_node/tasks/
/agent/roles/install_agent_node/tasks/main.yml
...
```
I am using a react editor, and loads the validation file like that:
```typescript
configureMonacoYaml(monaco, {
      enableSchemaRequest: true,
      schemas: [
        {
          // If YAML file is opened matching this glob
          fileMatch: ['**/roles/**/tasks/*.yml'],
          //  NOT WORKING - I TRIED EVERY VALUES
          uri: 'https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/?',
        },
        {
          // If YAML file is opened matching this glob
          fileMatch: ['*.yml'],
          // Then this schema will be downloaded from the internet and used.
          uri: 'https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook',
        },
      ],
    });
```
For example, my role /agent/roles/install_agent_docker/tasks/main.yml is:
```yaml
- name: Setup agent files
  include_role:
    name: install_agent_docker_conf

- name: Docker installation if needed
  include_role:
    name: install_docker

- name: Setup Docker configuration file
  include_role:
    name: install_agent_docker_conf

- name: Remove Docker volume if present
  include_role:
    name: remove_agent_docker_volume

- name: Start Docker agent service
  include_role:
    name: start_agent_docker
```

I try every $defs in the file (task, tasks, play, play-role, etc...) and none of them worked. 
--> The def is loaded, but the schema obviously is raising errors in the editor, saying the syntax/keywords are incorrect.

**Note that is working perfectly for the root playbooks.**

Here is the full directory:
https://github.com/SquirrelCorporation/SquirrelServersManager/tree/master/server/src/ansible/00000000-0000-0000-0000-000000000000/agent
