### DISCUSSION TITLE
Dev version installed by ansible-lint action

### DISCUSSION THREAD

**Discussion by mkravchuk-godaddy** [ansible/ansible-lint#4562] [Q&A]
Is it okay that during working ansible-lint action, it is installing dev version of ansible-lint? To me, this is not obvious behavior...
```
- name: "Run ansible-lint"
  id: run-lint
  uses: ansible/ansible-lint@main
  with:
    args: ""
    requirements_file: ""
```
Successfully installed MarkupSafe-3.0.2 ansible-compat-25.1.4 ansible-core-2.18.3 ansible-lint-25.1.4.dev13 attrs-25.3.0 black-25.1.0 bracex-2.5.post1 cffi-1.17.1 click-8.1.8 cryptography-44.0.2 filelock-3.18.0 importlib-metadata-8.6.1 jinja2-3.1.6 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 mypy-extensions-1.0.0 packaging-24.2 pathspec-0.12.1 platformdirs-4.3.7 pycparser-2.22 pyyaml-6.0.2 referencing-0.36.2 resolvelib-1.0.1 rpds-py-0.23.1 ruamel.yaml-0.18.10 ruamel.yaml.clib-0.2.12 subprocess-tee-0.4.2 typing-extensions-4.12.2 wcmatch-10.0 yamllint-1.37.0 zipp-3.21.0
**ansible-lint 25.1.4.dev13** using ansible-core:2.18.3 ansible-compat:25.1.4 ruamel-yaml:0.18.10 ruamel-yaml-clib:0.2.12
