### ISSUE TITLE
Configurable violation ignore list file

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#1584]
##### Summary

I would like to implement a configurable option for silencing specific errors similar to the one used by flake8, where you can acknowledge and ignore specific errors inside specific files, even mentioning the line numbers of you want.

If we do this we may even avoid the need to add YAML comments with noqa, which can be really spammy and only record exceptions in ignore.txt files, very similar with what ansible-test does now.

##### Details

While initially this can be implemented as a feature, it does open the door of removing ruyaml loading completely and rely on pyyaml alone, simplifying the corebase considerably.

Still, decision about if we should remove noqa comments or not should require a wider community consultation.

Example from flake8 config:
```
per-file-ignores =
  docs/conf.py: D
  src/molecule/test/*: D100,D103,D104
```
As one can see this allows to disable rules on files and patterns, being very easy to maintain.

Please use thumbs up down or comments to provide feedback on this proposal.

**Comment by ssbarnea** [comment]
I was looking at this proposal and trying to find a good way to represent these ignores inside YAML as we don't want to parse the strings to implement it like pylint. I came with 3 ideas:

```
# new feature file rule skips (V1)
skips:
  git-latest:
    - "*.*"

# V2
skips:
  "*.*": git-latest

# V3 not the exclude_paths already exists at root level and has the same format, this one has
# the advantage of allowing use to add other rule specific configuration in the future.
rules:
  git-latest:
    exclude_paths:
      - "*.*"
```

WDYT?
