### ISSUE TITLE
Installing `git` fires [ANSIBLE0004]

### ISSUE THREAD

**Issue by publysher** [ansible/ansible-lint#16]
Example code:

```
- name: "Install Jenkins prerequisites"
  apt:
    pkg={{ item }}
    state=present
  sudo: yes
  with_items:
    - git
    - ruby
    - bundler
    - maven
    - openjdk-7-jdk
    - ttf-dejavu
    - ttf-bitstream-vera
```

Output:

```
[ANSIBLE0004] Checkouts must contain explicit version
roles/jenkins/tasks/main.yml:9
    - git
```

I think a `matchblock` instead of `match` is in order.
