### ISSUE TITLE
Reule request: Require all loops have a loop variable

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2038]
This is ok:

```
  loop:
    - red
    - green
    - blue
  loop_control:
    loop_var: rgb_color
```

This is not, no loop_var
```
  loop:
    - a
    - b
    - c
 ```
