### ISSUE TITLE
Allow ansible-lint to update role meta/main.yml galaxy_info information from the parent collection's meta

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2043]
With option of  --force
```
dependencies: No
galaxy_info:
  author: Yes
  company: Yes
  description: If not present
  galaxy_tags: 
  - Yes, if not present
  license: Yes
  min_ansible_version: Yes
```
