### ISSUE TITLE
no-free-form: add auto-fix support

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2116]
This one might be tricky because it will depend on the task, to it might only be best to start with a couple simple ones:

```yaml
  ansible.builtin.include_tasks: "{{ test_case_to_run }} ansible_connection=ansible.netcommon.network_cli connection={{ cli }}"
```
should be 
```yaml
- ansible.builtin.include_tasks: "{{ test_case_to_run }}"
  vars:
    ansible_connection: ansible.netcommon.network_cli 
    connection: "{{ cli }}"
```

and 

```yaml
- debug: msg="END connection={{ ansible_connection }} nxos_linkagg sanity test"
```
should be
```yaml
- debug: 
    msg: "END connection={{ ansible_connection }} nxos_linkagg sanity test"
```

Even if we only could do debug, import and include it would be cool.

Feel free to decline, but I thought it might be an interesting challenge since the `=` format is very specific to ansible
