### ISSUE TITLE
Double yml syntax shouldn't be allowed

### ISSUE THREAD

**Issue by tristanbes** [ansible/ansible-lint#214]
# Issue Type
- Feature request
# Ansible and Ansible Lint details

```
ansible 2.1.2.0
ansible-lint 3.3.3
```
# Desired Behaviour

When using this (which is wrong, but it happened to me) 

```
- name: Update git config
  template: >
    src: install_from_git/gitconfig
    dest: "{{ yprox_version_dir }}/.git/config"
```

**instead of**

```
- name: Update git config
  template: 
    src: install_from_git/gitconfig
    dest: "{{ yprox_version_dir }}/.git/config"
```

It should trigger an error/warning about how the 2 argument `dest` will be ignored so the module `template` will throw an error.
# Actual Behaviour (Bug report only)

Ansible lint doesn't throw an error
