### ISSUE TITLE
jinja[spacing] suggestion doesn't cope well with multi-line code

### ISSUE THREAD

**Issue by evgeni** [ansible/ansible-lint#2313]
##### Summary

When a Jinja expression spans multiple lines, the suggested change in the `ansible-lint` output is only displaying the last line.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
% ansible --version
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/evgeni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/a/venv/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/evgeni/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/a/venv/bin/ansible
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.1.2
  libyaml = True


% ansible-lint --version
ansible-lint 6.5.0 using ansible 2.13.3
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Fedora 36, but irrelevant

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  vars:
    a: true
    b: false
  tasks:
    - name: Print stuff
      ansible.builtin.debug:
        msg: "{{ [
            a | ternary('Red Hat Enterprise Linux Server', ''),
            b | ternary('Red Hat Enterprise Linux for x86_64', '')
          ] | select() | list }}"
```

```console (paste below)
% ansible-lint lol.yml   
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: lol.yml
WARNING  Listing 1 violation(s) that are fatal
jinja: Jinja2 spacing could be improved: {{ [ a | ternary('Red Hat Enterprise Linux Server', ''), b | ternary('Red Hat Enterprise Linux for x86_64', '') ] | select() | list }} -> {{ [a | ternary('Red Hat Enterprise Linux Server', ''), b | ternary('Red Hat Enterprise Linux for x86_64', '')] | select() | list }} (jinja[spacing])
lol.yml:7 Jinja2 template rewrite recommendation: `{{  | select() | list }}`.

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - jinja[spacing]  # Rule that looks inside jinja2 templates.

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

##### Desired Behavior

The "rewrite recommendation" should contain the "correct" recommendation ;-)

##### Actual Behavior

See reproducer above.

Interestingly, the "jinja" prefixed line has the correct changes reported, but not the "lol.yml:7" one, so the data is getting lost somewhere in the reporting stack?
