### ISSUE TITLE
jinja[spacing] false positive tracker for v6.5.1

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#2338]
##### Summary

We know that even 6.5.1 produce some bad jinja formatting suggestions and we plan to remediate them as soon as possible. We will use this ticket to document them, so check the current list and if you have other examples, please minimize them first and add them in a comment. 

##### Known false positives

```
```

**Comment by max06** [comment]
As requested:

---

```yaml
- name: Spacing Demo
  ansible.builtin.debug:
    msg: "{{ foo[bar | baz] }}"
```
-> Linter doesn't like the space after the pipe.

---

```yaml
- name: Spacing Demo
  ansible.builtin.debug:
    msg: "{{ [{'foo': bar, 'baz': blah}] }}" # The array-[] confuses the linter
```
-> Linter wants to have spaces after colons removed, if it's in an array.
