### ISSUE TITLE
jinja: should not report undefined variable for defined variable

### ISSUE THREAD

**Issue by erikgb** [ansible/ansible-lint#2447]
##### Summary

Ansible-lint reports undefined variable on a defined variable when variable is used in Jinja expression.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
ansible [core 2.13.4]
  config file = None
  configured module search path = ['/home/erikbo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/erikbo/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True

ansible-lint --version
ansible-lint 6.6.0 using ansible 2.13.4
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Not applicable

##### STEPS TO REPRODUCE

Given this simple playbook (`test.yml`):

```yaml
---
- name: Ansible Lint to_nice_yaml bug
  hosts: localhost
  connection: local
  tasks:
    - name: Set test fact
      ansible.builtin.set_fact:
        my_yaml_var:
          clusters:
            - cluster:
                server: foo:443
              name: foo-cluster:443
      register: updated

    - name: Update test fact
      ansible.utils.update_fact:
        updates:
          - path: "my_yaml_var.clusters[0].cluster.server"
            value: "https://bar:6443"
      register: updated

    - name: Debug updated test fact
      ansible.builtin.debug:
        msg: "{{ updated.my_yaml_var | to_yaml }}"
```

##### Desired Behavior

Should not report any lint issues, as the variable is obviously defined.

##### Actual Behavior

Running `ansible-lint test.yml`:

```paste below
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: test.yml
WARNING  Listing 1 violation(s) that are fatal
jinja: to_yaml - 'updated' is undefined. 'updated' is undefined (jinja[invalid])
test.yml:22 Task/Handler: Debug updated test fact

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - jinja[invalid]  # Rule that looks inside jinja2 templates.

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

Running the playbook works fine: `ansible-playbook test.yml`

```paste
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Ansible Lint to_nice_yaml bug] ***************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Set test fact] *******************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Update test fact] ****************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Debug updated test fact] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "clusters:\n- cluster: {server: 'https://bar:6443'}\n  name: foo-cluster:443\n"
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by briantist** [comment]
I'm seeing what seems like the same behavior when using `register:`ed variables in jinja tests, for example:

```
---
- name: Ansible Lint to_nice_yaml bug
  hosts: localhost
  connection: local
  tasks:
    - name: Set test fact
      ansible.builtin.set_fact:
        my_yaml_var:
          clusters:
            - cluster:
                server: foo:443
              name: foo-cluster:443
      register: updated

    - name: Passes
      when: updated is changed
      ansible.builtin.debug:
        msg: "hi"

    - name: Fails
      vars:
        has_changed: "{{ updated is changed }}"  # fails
      ansible.builtin.debug:
        msg: "{{ updated is changed }}"  # also fails
```

This shows up as:
```
jinja: The 'changed' test expects a dictionary (jinja[invalid])
```

If I change the references to like `{{ updated | default({}) is changed }}` then they will work, but that's ugly and confusing.

Clearly ansible-lint knows that it's ok when used in the `when` keyword, but if it's referenced in the task call, even implicitly via vars, it will fail.
