### ISSUE TITLE
docs: copy/template rule needs better reasoning

### ISSUE THREAD

**Issue by greg-hellings** [ansible/ansible-lint#2501]
##### Summary

template-instead-of-copy rule finds false positive when `content` argument is used that has template values in it.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

Linux/NixOS

##### STEPS TO REPRODUCE

Sample play
```yaml
- name: Write file contents from variable
  ansible.builtin.copy:
    dest: /some/dest/path
    content: "{{ some_var.subfield }}"
```

##### Desired Behavior

The above code should be perfectly acceptable, as all templating will be handled locally within the file.

##### Actual Behavior

Error `template-instead-of-copy` is thrown.
