### ISSUE TITLE
key-order warning when using block with when condition

### ISSUE THREAD

**Issue by netsandbox** [ansible/ansible-lint#2509]
##### Summary

key-order warning when using block with when condition.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
ansible [core 2.12.9]
  config file = /home/ansible/code/git/ansible/ansible.cfg
  configured module search path = ['/home/ansible/code/git/ansible/modules']
  ansible python module location = /home/ansible/code/git/ansible/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ansible/code/git/ansible/collections
  executable location = /home/ansible/code/git/ansible/venv/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True

ansible-lint --version
ansible-lint 6.7.0 using ansible 2.12.9
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

NA

##### STEPS TO REPRODUCE

Create playbook based on https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html#grouping-tasks-with-blocks:

```yaml
- name: Test
  hosts: all
  tasks:
  - name: Handle the error
    block:
      - name: Print a message
        ansible.builtin.debug:
          msg: 'I execute normally'
    when: ansible_facts.distribution == 'CentOS'
```

```console
$ ansible-lint playbook.yml 
WARNING  Listing 1 violation(s) that are fatal
key-order: You can improve the task key order to: name, when, block (key-order[task])
playbook.yml:4 Task/Handler: Handle the error
```

##### Desired Behavior

No warning for the above playbook.

##### Actual Behavior

```
WARNING  Listing 1 violation(s) that are fatal
key-order: You can improve the task key order to: name, when, block (key-order[task])
playbooks/test.yml:4 Task/Handler: Handle the error
```
