### ISSUE TITLE
False EANSIBLE0016 when checking if task NOT changed

### ISSUE THREAD

**Issue by strangeman** [ansible/ansible-lint#258]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.3.0.0
ansible-lint 3.4.12
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

```
  - name: backup server configs
    win_shell: cp C:\ProgramData\App\{{ app_name }}.config C:\ProgramData\App\{{ app_name }}.config{{ backup_postfix }}
    args:
      removes: C:\ProgramData\App\{{ app_name }}.config

  - name: copy server configs
    win_template:
      src: "{{ deploy_env }}/apps/{{ app_name }}.xml.j2"
      dest: "C:\ProgramData\App\{{ app_name }}.config"
    register: app_config

  - name: delete backup because config file wasn't changed
    win_file:
      path: C:\ProgramData\App\{{ app_name }}.config{{ backup_postfix }}
      state: absent
    when: not (app_config|changed)
```
Third task shouldn't raise `[EANSIBLE0016] Tasks that run when changed should likely be handlers`, because there is nothing like handlers logic

# Actual Behaviour (Bug report only)

Ansible-lint show error `[EANSIBLE0016] Tasks that run when changed should likely be handlers`
