### ISSUE TITLE
False positive EANSIBLE0014 also flags vars in shell task

### ISSUE THREAD

**Issue by queria** [ansible/ansible-lint#275]
# Issue Type
- Bug report

# Ansible and Ansible Lint details
```
ansible --version
ansible 2.3.0.0
ansible-lint --version
ansible-lint 3.4.13
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

EANSIBLE0014 should validate only command task, not shell.

# Actual Behaviour (Bug report only)

When ansible-lint validating playbook with shell tasks with env vars
```
- hosts: "localhost"
  gather_facts: no
  become: no
  tasks:
      - shell: 'MYVAR="$(date)" env | grep MY'
```
it fails and complains about Env vars shouldn't be in command
```
test-play.yaml:5: [EANSIBLE0014] Environment variables don't work as part of command
```
