### ISSUE TITLE
run_once[task] incorrectly fails

### ISSUE THREAD

**Issue by jkossis** [ansible/ansible-lint#2815]
##### Summary

The run_once linting rule incorrectly fails when using run_once within a task, along with the default playbook strategy (linear).

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```
ansible-lint 6.9.1 using ansible 2.14.1
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

The subsequent code block yields this ansible-lint error: 

`Using run_once may behave differently if strategy is set to free.ansible-lint[run_once[task]](https://ansible-lint.readthedocs.io/rules/run-once/)`

```
- name: This is a test playbook
  hosts: all
  strategy: linear
  tasks:
    - name: This is a test task
      ansible.builtin.debug:
        msg: "Hello World!"
      run_once: true
```

##### Desired Behavior

That code block above should be valid, as the strategy is set to `linear` (and not `free`). 

##### Actual Behavior

It seems pretty straightforward as to why this is occurring. When taking a look at the `matchtask` function added [here](https://github.com/ansible/ansible-lint/pull/2626/files#diff-3177d7c4deb1f71b95aafee3cde94e887987007d8862080f1b55cb85d9cf5f34), you can see that it only checks for `run_once`, and doesn't take into account the strategy (like its sibling `matchplay` function does). Additionally, the examples/tests included in that PR don't cover this case. They only cover not using `run_once` at all, or using it with the `free` strategy.
