### ISSUE TITLE
`args[module]: one of the following is required: state, enabled` for `service`

### ISSUE THREAD

**Issue by Vanav** [ansible/ansible-lint#2829]
Role:
```
- name: Check if service is down (test)
  service:
    name: '{{ env_name }}@1'
  register: service_details
```

`ansible-lint`:
```
args[module]: one of the following is required: state, enabled (warning)
tasks/deploy-services.yml:33 Task/Handler: Check if service is down (test)
...
You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental

                  Rule Violation Summary                   
 count tag          profile rule associated tags           
     3 args[module]         syntax, experimental (warning) 
```
`state` or `enabled` are not required for `service` actually. But [docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html) say there is requirement. I use this syntax to get state of service. Maybe we should update Ansible docs to remove "requirement"?

Full code that checks, if service is down, and fails, if service goes down:
```
- name: Check if service is down
  service:
    name: '{{ env_name }}@1'
  register: service_details
  until: service_details.status.ActiveState != "active"
  failed_when: service_details.status.ActiveState != "active"
  retries: 5
  delay: 1
  become: true
```
