### ISSUE TITLE
Valid module arguments are reported as `args[module]` violations in ansible-lint 6.10.0

### ISSUE THREAD

**Issue by piotrp** [ansible/ansible-lint#2830]
ansible-lint 6.10.0 doesn't recognize `use_ssh_args` argument of `synchronize` module (but recognizes nonexistent `ssh_args`).

Playbook:
```yml
- name: Test
  hosts: localhost
  tasks:
    - name: Copy files
      synchronize:
        src: .
        dest: .
        owner: false
        group: false
        use_ssh_args: true
```

Output:
```
$ ansible-lint synchronize-test.yml
WARNING  Skipped installing collection dependencies due to running in offline mode.
WARNING  Listing 1 violation(s) that are fatal
args[module]: Unsupported parameters for synchronize module: use_ssh_args. Supported parameters include: set_remote_user, rsync_opts, times, copy_links, _local_rsync_path, recursive, rsync_path, rsync_timeout, dirs, delete, group, src, compress, dest_port, ssh_connection_multiplexing, delay_updates, ssh_args, partial, link_dest, _local_rsync_password, _substitute_controller, verify_host, links, owner, mode, existing_only, checksum, archive, perms, private_key, dest. (warning)
synchronize-test.yml:4 Task/Handler: Copy files

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental

                  Rule Violation Summary
 count tag          profile rule associated tags
     1 args[module]         syntax, experimental (warning)

Passed with production profile, 5/5 star rating: 0 failure(s), 1 warning(s) on 1 files.
```

I also see an issue in how things are worded in output: ansible-lint prints "Listing 1 violation(s) that are fatal" but also "Passed with production profile, 5/5 star rating: 0 failure(s), 1 warning(s) on 1 files." and exits with `0` - so it it fatal or not?
