### ISSUE TITLE
Tasks schema accepts  unknown keys or multiple modules

### ISSUE THREAD

**Issue by burn2l** [ansible/ansible-lint#2916]
- Bug report
If a task has more than 1 modules or an illegal key the tasks schema will accept it while ansible-lint will correctly reject it.
```
- name: Copy Nginx Coniguration
  template:
    src: nginx.conf.j2
    dest: nginx1.conf
  xyz: bah
```
The above task is accepted by the tasks schema but ansible-lint fails with:
_parser-error: conflicting action statements: template, xyz_

- Ansible and Ansible Lint details
ansible-lint 6.11.0 using ansible 2.13.6

- Desired Behavior
Since the set of legal modules is open-ended, could the tasks schema accept only 1 "unknown" key?
