### ISSUE TITLE
noqa doesn't work for run_once[play]: Play uses strategy: free (warning) playbook.yml:1

### ISSUE THREAD

**Issue by donvipre** [ansible/ansible-lint#2932]
##### Summary

In below playbook the ansible-lint playbook.yml throws the warning run_once[play].
It appears to detect the linter exception on line 1.
Tried the noqa statement on line 1 as well.

playbook looks like the following:

```yaml
---
# system update
- name: Play - system update
  hosts: all:!localhost
  strategy: free # noqa run_once[play]
  serial: 10
  roles:
    - role: 'ansible-role-system-update'
```

Output of ansible-lint:

```bash
ansible-lint system_update.yml 
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: system_update.yml
WARNING  Listing 1 violation(s) that are fatal
run_once[play]: Play uses strategy: free (warning)
system_update.yml:1

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - experimental  # all rules tagged as experimental

                   Rule Violation Summary                   
 count tag            profile rule associated tags          
     1 run_once[play]         idiom, experimental (warning) 

Passed with production profile, 5/5 star rating: 0 failure(s), 1 warning(s) on 1 files.
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

Fedora 37

```bash
ansible-lint --version
ansible-lint 6.10.0 using ansible 2.14.1
```

- ansible installation method: OS package Fedora
- ansible-lint installation method: OS package Fedora

##### STEPS TO REPRODUCE

See above in the introduction.

##### Desired Behavior

`# noqa` behind the `strategy: free`  should ignore the warning.

##### Actual Behavior

See above in the introduction.
