### ISSUE TITLE
Load-failure when importing playbook from another collection using its FQCN

### ISSUE THREAD

**Issue by mac-roche** [ansible/ansible-lint#2936]
# Summary

ansible-lint throws a load-failure error as soon as there is a playbook having an "import_playbook" task that uses the FQCN. The playbook is located in another ansible collection.

# Issue Type

- Bug report

# Ansible and Ansible Lint details

```
ansible --version
ansible [core 2.13.7]
ansible-lint --version
ansible-lint 6.11.0 using ansible 2.13.7
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behavior

ansible-lint accepts FQCN (namespace.collectionname.playbookname) to run an "import_playbook" task, even though it originates from another collection.

# Actual Behavior (Bug report only)

Playbook in collection some.collection:
```
- name: Test
  tasks:
    - name: Import Playbook from another.collection
      ansible.builtin.import_playbook: another.collection.play
```

Execution of ansible-lint:

```
ansible-lint -v
[...]
load-failure[filenotfounderror]: [Errno 2] No such file or directory: '/home/users/USERID/.ansible/collections/ansible_collections/some/collection/another.collection.play'
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
