### ISSUE TITLE
args[module] reports fails for mutually exclusive arguments although they are default(omit)

### ISSUE THREAD

**Issue by ianw** [ansible/ansible-lint#2962]
##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint 6.11.0 using ansible 2.14.2
```

The following call

```yaml
- name: Add apt keys
  become: true
  apt_key:
    url: "{{ zj_item['url'] | default(omit) }}"
    data: "{{ zj_item['data'] | default(omit) }}"
  loop: "{{ repositories_keys }}"
  loop_control:
    loop_var: zj_item
```

reports

```
roles/ensure-package-repositories/tasks/Debian.yaml:8: args[module]: parameters are mutually exclusive: data|file|keyserver|url (warning)
```

I guess it is true that the arguments are mutually exclusive, but also because they're ```default(omit)``` only one is coming in, making it valid code.

Feels like a bit of a tricky one, because the code could be correct, but it would be hard to determine statically.  I guess you could split it up into multiple calls behind ```when:``` statements, but at the cost of extra task overheads.  Perhaps ```default(omit)``` arguments should be ignored for mutually-exclusive argument checking?
