### ISSUE TITLE
Version 6.12.0 contains regression for resolving modules/actions.

### ISSUE THREAD

**Issue by TylerJang27** [ansible/ansible-lint#2969]
##### Summary

Ansible-lint fails to resolve some modules/actions in playbooks.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version  # 6.12.0
```

- ansible-lint installation method: pip installed (using [trunk](https://docs.trunk.io/docs/check)) on Ubuntu 20.04.5 LTS

##### STEPS TO REPRODUCE

```yaml
# jboss-standalone/demo-aws-launch.yml (relative to workspace)
---
- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
    - group_vars/all

  tasks:
    - name: Launch instances
      ec2:
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        keypair: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        region: "{{ ec2_region }}"
        instance_tags:
          "{'ansible_group':'jboss', 'type':'{{ ec2_instance_type }}', 'group':'{{
          ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
        count: "{{ ec2_instance_count }}"
        wait: true
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

```

```console (paste below)
ansible-lint
```

##### Desired Behavior

< 6.12.0 (specifically 6.11.0):
```
yaml[indentation]: Wrong indentation: expected 4 but found 2
.trunk/trunk.yaml:6

yaml[truthy]: Truthy value should be one of [false, true]
jboss-standalone/demo-aws-launch.yml:5

role-name: Role name ZbSoIn does not match ``^[a-z][a-z0-9_]*$`` pattern. (warning)
tmp/trunk-1001/ZbSoIn:1

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - yaml[indentation]  # Violations reported by yamllint.
  - yaml[truthy]  # Violations reported by yamllint.

                      Rule Violation Summary                      
 count tag               profile rule associated tags             
     1 role-name         basic   deprecations, metadata (warning) 
     1 yaml[indentation] basic   formatting, yaml                 
     1 yaml[truthy]      basic   formatting, yaml                 

Failed after min profile: 2 failure(s), 1 warning(s) on 14 files.
```
##### Actual Behavior

\>= 6.12.0:
```
syntax-check[specific]: couldn't resolve module/action 'ec2'. This often indicates a misspelling, missing collection, or incorrect module path.
jboss-standalone/demo-aws-launch.yml:12:7

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - syntax-check[specific]  # Ansible syntax check failed.

                  Rule Violation Summary                   
 count tag                    profile rule associated tags 
     1 syntax-check[specific] min     core                 

Failed after : 1 failure(s), 0 warning(s) on 14 files.
```

Issue was first identified when running [newly released version with trunk](https://github.com/trunk-io/plugins/actions/runs/4068099243/jobs/7006240066)
