### ISSUE TITLE
Tasks schema reports "block is a required property" when with_flattened is specified

### ISSUE THREAD

**Issue by burn2l** [ansible/ansible-lint#2978]
Other with_X options are accepted.

```
- name: with_flattened
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_flattened: "{{ items }}"
```

- Bug Report

```
ansible-lint 6.12.0 using ansible 2.13.6
```

**Comment by ajinkyau** [comment]
We can see that `with_flattened` has been moved under `community.general` since 2.10.
Correct usage: `community.general.with_flattened`.

**Comment by burn2l** [comment]
Strange ... when I run ansible-lint on:
```
- name: with_flattened
  ansible.builtin.debug:
    msg: "{{ item }}"
  community.general.with_flattened: "{{ items }}"
```
I get:
**parser-error: conflicting action statements: ansible.builtin.debug, community.general.with_flattened**

Note that with_indexed doesn't generate that error (unless I add community.general)
