### ISSUE TITLE
Some rules do not apply to tasks inside blocks

### ISSUE THREAD

**Issue by nlopez** [ansible/ansible-lint#355]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.6.1
ansible-lint 3.4.23
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

With a playbook like

```
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Get hostname
      command: hostname

    - name: Ansible block
      block:
        - name: Get hostname
          command: hostname
```

I expect both `command` tasks to match `ANSIBLE0012`

# Actual Behaviour

Only the `command` task outside the `block` is matched

```
❯ ansible-lint -v ~/test.yml       
Examining /Users/nlopez/test.yml of type playbook
[ANSIBLE0012] Commands should not change things if nothing needs doing
/Users/nlopez/test.yml:6
Task/Handler: Get hostname
```
