### ISSUE TITLE
var-naming[no-role-prefix] with dependencies that use - as separator

### ISSUE THREAD

**Issue by staticdev** [ansible/ansible-lint#3566]
##### Summary

I get an error that:

```
WARNING  Listing 1 violation(s) that are fatal
var-naming[no-role-prefix]: Variables names from within roles should use role_name_ as a prefix. (vars: visual_studio_code_users)
tasks/vscode.yml:6 Task/Handler: Install vscode

Read documentation for instructions on how to ignore specific rule violations.

                    Rule Violation Summary                     
 count tag                        profile rule associated tags 
     1 var-naming[no-role-prefix] basic   idiom
```

The problem is that my code prefixes the role name changing '-' with '_':

```
---
- name: Install vscode
  ansible.builtin.include_role:
    name: gantsign.visual-studio-code
  vars:
    visual_studio_code_users:
      - username: "{{ lookup('env', 'USER') }}"
        visual_studio_code_extensions: "{{ vscode_extensions }}"
```

If instead I use the real name as prefix I would have `visual-studio-code_users`, the problem is that I would get instead the errors:

```
WARNING  Listing 2 violation(s) that are fatal
var-naming[pattern]: Variables names should match ^[a-z_][a-z0-9_]*$ regex. (visual-studio-code_users)
tasks/vscode.yml:6

var-naming[pattern]: Variables names should match ^[a-z_][a-z0-9_]*$ regex. (visual-studio-code_users) (vars: visual-studio-code_users)
tasks/vscode.yml:6 Task/Handler: Install vscode

Read documentation for instructions on how to ignore specific rule violations.

                 Rule Violation Summary                 
 count tag                 profile rule associated tags 
     2 var-naming[pattern] basic   idiom
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 6.17.1 using ansible-core:2.14.4 ruamel-yaml:0.17.21 ruamel-yaml-clib:None
```

##### STEPS TO REPRODUCE

Just add the code above in a file, other than that my repo having the exact same error is https://github.com/staticdev/linux-workstation-playbook/pull/378

##### Desired Behavior

Having a way out.

##### Actual Behavior

Summary description has it all.
