### ISSUE TITLE
Feature request - Skip specific rule(s) for a specific task

### ISSUE THREAD

**Issue by Rickkwa** [ansible/ansible-lint#364]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible 2.4.0.0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

ansible-lint 3.4.23
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

Currently, we can skip linting on a task by adding `skip_ansible_lint` as a tag to the task. But I'm looking for something more granular than that. I want to be able to skip/ignore a specific rule (ie. `ANSIBLE00XX`) on a task-level basis. For example, something like:

```yaml
- hosts: ...
  tasks:
    - name: Install stuff
      yum:
        name: ...
        state: latest
      tags:
        - skip_ansible_lint_rule_ANSIBLE0010
```

Syntax is obviously tentative and subject to change.

In this example, I may indeed want to always install the `latest` version of a package, for whatever reason. I only want to ignore ANSIBLE0010 ("Package installs should not use latest"), but keep other linting like trailing whitespace.

**Comment by selivan** [comment]
I think it would also be convenient to have something like `.absible-lint.ignore` in project directory.

For example, I disagree with rule 405 "Remote package tasks should have a retry". Repository mirrors I use are quite reliable, I never encountered any problems. Failure to install package usually is because the repository is not properly configured, typo in the package name, problems with dependencies or something else, that can't be solved by retry.

**Comment by Rickkwa** [comment]
@selivan If I understood your situation correctly, that can be accomplished in the `.ansible-lint` [configuration file](https://docs.ansible.com/ansible-lint/configuring/configuring.html#configuration-file) using the `skip_list` property.

**Comment by selivan** [comment]
@Rickkwa Thanks, that should do the trick.

**Comment by awcrosby** [comment]
#460 has been raised to address this (WIP, tests and docs still needed), taking in several points of feedback here and in other issues. Here is the implementation so far (feedback welcome):
- If you add `# noqa [rule_id]` to the end of the line then the rule will be skipped
- If the rule is task-based (most are), the `# noqa [rule_id]` can be at the end of any line in the task
- If the rule is line-based, `# noqa [rule_id]` must be at the end of the particular line to be skipped
- You can skip multiple rules via a space-separated list `# noqa 201 402`

`tasks/main.yml`:
```
- name: ensure apache is at the latest version
  become_user: alice
  yum:
    name: httpd
    state: present
  when: my_var == true
- name: download file
  get_url:
    url: http://example.com/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/file.conf
    dest: "{{dest_proj_path}}/foo.conf"
```

```
(use_code) awc:role_test1$ ansible-lint -p .
/home/awc/code/role_test1/tasks/main.yml:4: [E405] Remote package tasks should have a retry
/home/awc/code/role_test1/tasks/main.yml:4: [E501] become_user requires become to work as expected
/home/awc/code/role_test1/tasks/main.yml:9: [E601] Don't compare to literal True/False
/home/awc/code/role_test1/tasks/main.yml:12: [E204] Lines should be no longer than 120 chars
/home/awc/code/role_test1/tasks/main.yml:13: [E206] Variables should have spaces before and after: {{ var_name }}
(use_code) awc:role_test1$ 
```
Updated `tasks/main.yml`:
```
- name: ensure apache is at the latest version
  become_user: alice
  yum:  # noqa 405 501
    name: httpd
    state: present
  when: my_var == true # noqa 601
- name: download file
  get_url:
    url: http://example.com/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/file.conf  # noqa 204
    dest: "{{dest_proj_path}}/foo.conf"  # noqa 206
```

```
(use_code) awc:role_test1$ ansible-lint -p .
(use_code) awc:role_test1$ 
```
