### ISSUE TITLE
Error: No file in /home/runner/work/ansible/ansible matched to [~/requirements.txt or **/pyproject.toml]

### ISSUE THREAD

**Issue by 0lzi** [ansible/ansible-lint#3648]
##### Summary

Using the GH action with the following .yml

```
---
name: ansible-lint
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.17.2
```

I get the following Error when running

`Error: No file in /home/runner/work/ansible/ansible matched to [~/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository`

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

Github Actions

##### STEPS TO REPRODUCE

Create `ansible-lint.yml` in `.github/workflows` folder

pasted 

```
---
name: ansible-lint
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.17.2
```
Push to new branch,get below error

```
Error: No file in /home/runner/work/ansible/ansible matched to [~/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
```

##### Desired Behavior

The action workflow runs ansible-lint on repository

##### Actual Behavior

Workflow fails

**Comment by ReenigneArcher** [comment]
I'm getting the same error after changed from the archived action.

But I do have a requirements.txt in the root of my repo and have checked out the repo.

```yml
jobs:
  ansible_lint:
    name: ansible lint
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ansible lint
        id: ansible-lint
        uses: ansible/ansible-lint@v6.17.2
        with:
          path: "playbooks/"
```
