### ISSUE TITLE
ansible-lint doesn't parse `include_tasks` files when using .ansible-lint

### ISSUE THREAD

**Issue by jkossis** [ansible/ansible-lint#3736]
##### Summary

When running ansible-lint with an .ansible-lint configuration file, `include_tasks` task files are not checked.

When running ansbile-lint without an .ansible-lint configuration file, `include_tasks` task files are correctly checked.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```
ansible-lint 6.19.0 using ansible-core:2.15.4 ansible-compat:4.1.10 ruamel-yaml:0.17.32 ruamel-yaml-clib:0.2.7
```

- ansible installation method: homebrew
- ansible-lint installation method: homebrew

##### STEPS TO REPRODUCE

.ansible-lint
```
#  content can be anything, but just using a simple example
use_default_rules: true
```

playbook.yml
```
- name: This is a playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Include other tasks
      ansible.builtin.include_tasks:
        file: ./other-tasks.yml
```

other-tasks.yml
```
# any lint error here will not be reported
```

##### Desired Behavior

When running ansbile-lint with or without an .ansible-lint configuration file, `include_tasks` task files are correctly checked.
