### ISSUE TITLE
GitHub Action is broken

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible-lint#3801]
##### Summary
```
> Run ansible/ansible-lint@main
> Run wget --output-file=.git/ansible-lint-requirements.txt https://raw.githubusercontent.com/ansible/ansible-lint/main/.config/requirements-lock.txt
wget: .git/ansible-lint-requirements.txt: No such file or directory
Error: Process completed with exit code 1.
```

See https://github.com/ansible-collections/community.internal_test_tools/actions/runs/6368221917/job/17287439044

##### Issue Type
- Bug Report

**Comment by jasonramey** [comment]
I believe this is due to using `--output-file` which according to my local wget installation, is for logging messages?
```
-o,  --output-file=FILE          log messages to FILE
```
if I change it to use:
```
-O,  --output-document=FILE      write documents to FILE
```
it works fine. could this be an upstream change to the ubuntu-latest image?

**Comment by ssbarnea** [comment]
Can someone find a place that documents the difference between one option and another? `--help` does not bring any clarifications.

**Comment by felixfontein** [comment]
Well, the action still fails. I now looked at its changes (https://github.com/ansible/ansible-lint/commits/main/action.yml), and I guess the reason is pretty obvious: https://github.com/ansible/ansible-lint/commit/55b8b667587295d4fdbbd2f9c90a84455f6ece99 removed the `actions/checkout@v4` call from the action, and now assumes that the caller does that. Which is quite a breaking change, despite being released in a bugfix release (https://github.com/ansible/ansible-lint/releases/tag/v6.20.2).

**Comment by jamesholland-uk** [comment]
Thanks for jumping on this fast. The testing for our Collection with `ansible-lint` broke due to this issue. If [this](https://github.com/ansible-collections/community.internal_test_tools/pull/101) is merged, are we expecting it to still be failing with `.git/ansible-lint-requirements.txt: No such file or directory`?
```
    name: Ansible Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
```
