### ISSUE TITLE
--fix mangles tasks using "=" formatting

### ISSUE THREAD

**Issue by tremble** [ansible/ansible-lint#3940]
##### Summary

if a task uses the old `some_key=` format ansible-lint --fix mangles it

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint 6.22.1 using ansible-core:2.17.0.dev0 ansible-compat:4.1.10 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.8
```

- ansible installation method: source
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

running `ansible-lint --fix` against the example YAML results in a junk return value: 

```yaml
- name: example playbook
  hosts: localhost
  tasks:
    - debug: msg='Hello there world'
```

##### Desired Behavior

```yaml
---
- name: Example playbook
  hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: "Hello there world"
```

##### Actual Behavior

```yaml
---
- name: Example playbook
  hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: "'Hello"
        cmd: there world'
```
