### ISSUE TITLE
ansible-lint failes with reboot module and python 3.7

### ISSUE THREAD

**Issue by mhubig** [ansible/ansible-lint#395]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```shell
$ ansible --version
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/d0287062/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov  6 2018, 18:46:03) [Clang 10.0.0 (clang-1000.11.45.5)]
$ ansible-lint --version
ansible-lint 3.4.23
```

- ansible installation method: brew
- ansible-lint installation method: brew

# Desired Behaviour

ansible-lint should not report the new [reboot module](https://docs.ansible.com/ansible/2.7/modules/reboot_module.html) as error.

# Actual Behaviour (Bug report only)

Given this playbook:
```yml
- hosts: all
  tasks:
    - name: Restarting the system
      reboot:
```

I get this error:
```shell
$ ansible-lint test.yml
Couldn't parse task at test.yml:3 (no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '<unicode string>': line 3, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

(could not open file to display line))
{'name': 'Restarting the system', 'reboot': None}
```

**Comment by gundalow** [comment]
This works as expected for me
```
cat ansible-lint-395-reboot.yml
- hosts: all
  tasks:
    - name: Restarting the system
      reboot:
```


````
ansible-lint -vvv ansible-lint-395-reboot.yml
Examining ansible-lint-395-reboot.yml of type playbook
```

What's on line 3 column 7, that unicode string looks like it might be causing issues
