### ISSUE TITLE
Using certian community modules breaks linting due to naming restrictions

### ISSUE THREAD

**Issue by wlfshmn** [ansible/ansible-lint#3981]
##### Summary

Using modules whose names don't comply with expected syntax, but are nonetheless accepted galaxy modules (https://galaxy.ansible.com/ui/repo/published/lvrfrc87/git_acp/) breaks linting, and does so early. Nor can syntax rules be supressed by noqa.

```
 WARNING  Listing 1 violation(s) that are fatal
14:54:33  roles/myrole/tasks/main.yml:87:7: syntax-check[unknown-module]: couldn't resolve module/action 'lvrfrc87.git_acp.git_acp'. This often indicates a misspelling, missing collection, or incorrect module path.
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

##### STEPS TO REPRODUCE

```
console (paste below)
    - name: Add/Commit/Push rewritten modules.csv file
      environment:
        GIT_AUTHOR_NAME: "{{ module_changes.author_name }}"
        GIT_AUTHOR_EMAIL: "{{ module_changes.author_email }}"
        GIT_COMMITTER_NAME: "{{ module_changes.author_name }}"
        GIT_COMMITTER_EMAIL: "{{ module_changes.author_email }}"
      lvrfrc87.git_acp.git_acp:  # noqa: no-handler syntax-check[unknown-module]
        path: "{{ temporary_local_deploy_repository.path }}"
        branch: "{{ module_repo_branch }}"
        comment: "Pipeline module update"
        add: ["{{ module_repo_subdirectory }}/modules.csv"]
        push: true
        url: "https://{{ github_pat_user }}:{{ github_pat }}@{{ module_repo_url }}"
      when: csv_rewrite.changed
```

##### Desired Behavior

Expected behavior would be a full lint result

Either allow the full breadth of module names that galaxy allows, or allow suppression of these syntax errors.

##### Actual Behavior

linting breaks and refuses to report additional issues

```
 WARNING  Listing 1 violation(s) that are fatal
14:54:33  roles/myrole/tasks/main.yml:87:7: syntax-check[unknown-module]: couldn't resolve module/action 'lvrfrc87.git_acp.git_acp'. This often indicates a misspelling, missing collection, or incorrect module path.
```
