### ISSUE TITLE
Hexadecimal value broken by `ansible-lint --fix`

### ISSUE THREAD

**Issue by sajattack** [ansible/ansible-lint#4023]
##### Summary

Following the example on the [win_regedit docs](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_regedit_module.html)
```yml
- name: Add or update registry path MyCompany, with dword entry 'hello', and containing 0xff2500ae as the hex value
  ansible.windows.win_regedit:
    path: HKCU:\Software\MyCompany
    name: hello
    data: 0xff2500ae
    type: dword
```

and changing it slightly to

```yml
 - name: IIS | Enable Remote Management
   win_regedit:
     path: HKLM:\Software\Microsoft\WebManagement\Server
     name: EnableRemoteManagement
     data: 0x1
     type: dword
```

and running `ansible-lint --fix` (all)

produces this diff

```diff
 - name: IIS | Enable Remote Management
-  win_regedit:
+  ansible.windows.win_regedit:
     path: HKLM:\Software\Microsoft\WebManagement\Server
     name: EnableRemoteManagement
-    data: 0x1
+    data: "01"
     type: dword
-
+
```

I consider the original notation more correct (and the docs seem to agree), and it seems likely that the "fixed" code might not even run correctly (though I haven't tested)

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT
Windows / WSL Debian
```console (paste below)
ansible-lint 24.2.0 using ansible-core:2.14.3 ansible-compat:4.1.11 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.7
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

see summary

see summary

see summary

##### Actual Behavior

see summary
