### ISSUE TITLE
Tasks with attributes formatted as key=value pairs get reformatted incorrectly

### ISSUE THREAD

**Issue by zack-mayoh** [ansible/ansible-lint#4189]
##### Summary

`ansible-lint --fix` incorrectly reformats tasks with attributes originally formatted as `key=value` pairs by splitting the fact's value and adding the second part to an invalid `cmd` attribute.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint 6.22.2 using ansible-core:2.14.9 ansible-compat:4.1.11 ruamel-yaml:None ruamel-yaml-clib:None
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Run `ansible-lint --fix` on the following test playbook:

```yaml
---
- name: Test set_fact
  hosts: all
  tasks:
    - name: Set boolean fact
      ansible.builtin.set_fact: foo=true

    - name: Set string fact with spaces
      ansible.builtin.set_fact: foo="String with spaces"

    - name: File task
      ansible.builtin.file: path=/tmp/config state=directory mode=0755

```

##### Desired Behavior

Resulting formatted playbook should be:

```yaml
- name: Test set_fact
  hosts: all
  tasks:
    - name: Set boolean fact
      ansible.builtin.set_fact:
        foo: "True"

    - name: Set string fact with spaces
      ansible.builtin.set_fact:
        foo: "String with spaces"

    - name: File task
      ansible.builtin.file:
        path: /tmp/config
        state: directory
        mode: "0755"
```

##### Actual Behavior

Actual resulting formatted playbook:

```yaml
---
- name: Test set_fact
  hosts: all
  tasks:
    - name: Set boolean fact
      ansible.builtin.set_fact:

        foo: "True"
        cmd: ""
    - name: Set string fact with spaces
      ansible.builtin.set_fact:

        foo: '"String'
        cmd: with spaces"
    - name: File task
      ansible.builtin.file:

        path: /tmp/config
        state: directory
        mode: "0755"
        cmd: ""

```
Problems:
- The boolean `set_fact` and `file` tasks have an empty `cmd` attribute added to them
- The string `set_fact` has everything in the fact string after the first space put in a `cmd` attribute
