### ISSUE TITLE
`--fix` will change the comment indentation level when there is no following code

### ISSUE THREAD

**Issue by ddeepwell** [ansible/ansible-lint#4260]
##### Summary

`ansible-lint --fix` will reduce the comment level of comments that are at the end of a block in the .yamllint file.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 24.7.0 using ansible-core:2.17.1 ansible-compat:24.7.0 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Using the following `.yamllint `file, `ansible-lint --fix` will reduce the comment level of the commented "quoted-strings" section.

`.yamllint` file:
```yaml
---
extends: default
rules:
  comments:
    # https://github.com/prettier/prettier/issues/6780
    min-spaces-from-content: 1
  # https://github.com/adrienverge/yamllint/issues/384
  comments-indentation: false
  line-length:
    max: 88
  # We are adding an extra space inside braces as that's how prettier does it
  # and we are trying not to fight other linters.
  braces:
    min-spaces-inside: 0 # yamllint defaults to 0
    max-spaces-inside: 1 # yamllint defaults to 0
  # key-duplicates:
  #   forbid-duplicated-merge-keys: true # not enabled by default
  octal-values:
    forbid-implicit-octal: true # yamllint defaults to false
    forbid-explicit-octal: true # yamllint defaults to false
  # quoted-strings:
  #   quote-type: double
  #   required: only-when-needed

ignore:
  - secrets.yml

```

##### Desired Behavior

Expected the comment indentation level to not be changed.

##### Actual Behavior

The resultant `.yamllint` file after running `ansible-lint --fix` is:

```yaml
---
extends: default
rules:
  comments:
    # https://github.com/prettier/prettier/issues/6780
    min-spaces-from-content: 1
  # https://github.com/adrienverge/yamllint/issues/384
  comments-indentation: false
  line-length:
    max: 88
  # We are adding an extra space inside braces as that's how prettier does it
  # and we are trying not to fight other linters.
  braces:
    min-spaces-inside: 0 # yamllint defaults to 0
    max-spaces-inside: 1 # yamllint defaults to 0
  # key-duplicates:
  #   forbid-duplicated-merge-keys: true # not enabled by default
  octal-values:
    forbid-implicit-octal: true # yamllint defaults to false
    forbid-explicit-octal: true # yamllint defaults to false
# quoted-strings:
#   quote-type: double
#   required: only-when-needed

ignore:
  - secrets.yml
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
