### ISSUE TITLE
'with_community.general.filetree' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by 4wk-** [ansible/ansible-lint#4304]
##### SUMMARY

`ansible-lint` is complaining about attribute `with_community.general.filetree` not being valid. However, it's in [Ansible official documentation](https://docs.ansible.com/ansible/latest/collections/community/general/filetree_lookup.html). cf examples.

![image](https://github.com/user-attachments/assets/ea4b14b6-e944-4e23-97c3-29c9fd5e9fde)

Am I missing something?

##### ISSUE TYPE

- Bug Report

##### OS / ENVIRONMENT

Debian 12.6 in wsl2

```console (paste below)
$ ansible-lint --version
ansible-lint 24.7.0 using ansible-core:2.17.2 ansible-compat:24.7.0 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8
```

- ansible installation method: `pipx`
- ansible-lint installation method: `pipx`

##### STEPS TO REPRODUCE

```yml
---
- name: testing123
  hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Testing filetree
      ansible.builtin.template:
        src: "{{ item.path }}"
        dest: "/tmp/"
        owner: root
        group: root
        mode: '644'
      with_community.general.filetree: "templates/"
      when: item.state == 'file'
```

##### DESIRED BEHAVIOR
`ansible-lint` should not complain about `with_community.general.filetree`.

##### ACTUAL BEHAVIOR

```console
$ ansible-lint zplay.yml
WARNING  Listing 1 violation(s) that are fatal
syntax-check[specific]: 'with_community.general.filetree' is not a valid attribute for a Task
zplay.yml:11:7


                  Rule Violation Summary
 count tag                    profile rule associated tags
     1 syntax-check[specific] min     core, unskippable

Failed: 1 failure(s), 0 warning(s) on 1 files. Profile 'production' was required.
```
