### ISSUE TITLE
galaxy[tags] does not align between ansible-lint and galaxy-importer

### ISSUE THREAD

**Issue by minsis** [ansible/ansible-lint#4409]
##### Summary

The galaxy-importer library has some additional regex checks on the tags attribute that ansible-lint is missing.

In galaxy-importer you can see a regex is defined for tags where ansible-lint does not:
https://github.com/ansible/galaxy-importer/blob/master/galaxy_importer/constants.py#L47

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 24.9.0 using ansible-core:2.17.5 ansible-compat:24.9.1 ruamel-yaml:0.18.6 ruamel-yaml-clib:None
A new release of ansible-lint is available: 24.9.0 → 24.10.0 Upgrade by running: pip install --upgrade ansible-lint
```

- ansible installation method: conda
- ansible-lint installation method: conda

##### STEPS TO REPRODUCE

Create basic galaxy.yml file:
```yaml
name: test
namespace: test
description: test
repository: https://repo.com
authors:
  - me
readme: README.md
version: 1.0.0
tags:
  - application
  - tag1
  - tag2
  - tag-3
```

And run `ansible-lint galaxy.yml`

```console (paste below)
ansible-lint galaxy.yml
```

However when importing into galaxy there is a failure on `tag-3`

##### Desired Behavior

ansible-lint should fail on `tag-3`

##### Actual Behavior

ansible-lint passes validation

```paste below
Passed: 0 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'production'.
A new release of ansible-lint is available: 24.9.0 → 24.10.0 Upgrade by running: pip install --upgrade ansible-lint
```
