### ISSUE TITLE
become on import_playbook

### ISSUE THREAD

**Issue by SolomonHD** [ansible/ansible-lint#4418]
##### Summary
The linter has the following code as an error:
```yaml
- name: Import get_auth playbook
  ansible.builtin.import_playbook: integration.ghapp_auth.init_auth
  become: true
  vars:
    auth_additional_users:
      - ec2-user
```

`$[1] 'become' does not match any of the regexes: '^(ansible\\.builtin\\.)?import_playbook$', 'name', 'tags', 'vars', 'when'ansible-lint[schema[playbook]](https://ansible.readthedocs.io/projects/lint/rules/schema/)`
##### Issue Type

[import_playbook](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/import_playbook_module.html#attributes) supports the `become` keywords, idk why it says "none" in the support column.

**Comment by SolomonHD** [comment]
I don't understand, can you provide an example where this would not violate linter rules? FYI the following does NOT work:
```yaml
- name: Become does nothing here
  ansible.builtin.import_playbook: playbook_name.yml
  vars:
    become: true
```
