### ISSUE TITLE
ansible-lint 25.1.1 unable to find/use git when git URLs are used in requirements.yml

### ISSUE THREAD

**Issue by chriscroome** [ansible/ansible-lint#4498]
##### Summary

With the `25.1.1` version of `ansible-lint` I have this error:

> ansible was NOT installed successfully: could not find/use git

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```bash
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

ansible-lint --version
ansible-lint 25.1.1 using ansible-core:2.17.7 ansible-compat:25.1.0 ruamel-yaml:0.18.10 ruamel-yaml-clib:0.2.12

which git
/usr/bin/git

git --version
git version 2.39.5
```
- ansible installation method: `pipx` via [this role](https://git.coop/webarch/ansible)
- ansible-lint installation method: `pipx` via [this role](https://git.coop/webarch/ansible)

##### STEPS TO REPRODUCE

Add a git URL to a `requirements.yml` file, for example:

```bash
cat requirements.yml | head -n8
---
# Ansible managed

- name: ansible
  scm: git
  src: https://git.coop/webarch/ansible.git
  version: 3.40.0  # ansible
```

And run `ansible.lint .`

##### Desired Behavior

Previous version of `ansible-lint` worked fine with `requirements.yml` files containing git URLs.

##### Actual Behavior

This behaviour can be reproduced using [this repo](https://git.coop/webarch/localhost).

```bash
ansible-lint .
ERROR    [WARNING]: - ansible was NOT installed successfully: could not find/use git, it
is required to continue with installing https://git.coop/webarch/ansible.git
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
[/]
Got 1 exit code while running: ansible-galaxy role install -r /home/chris/webarch/localhost/requirements.yml --roles-path /home/chris/webarch/localhost/.ansible/roles
```

However if `ansible-galaxy role install` is run then the exit code is `0`:

```bash
ansible-galaxy role install -r /home/chris/webarch/localhost/requirements.yml --roles-path /home/chris/webarch/localhost/.ansible/roles
Starting galaxy role install process
- extracting ansible to /home/chris/ansible
- ansible (3.40.0) was installed successfull
...

echo $?
0
```

There is also no error with a `.pre-commit-config.yaml` containing:

```yaml
---
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.1.1
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        language: python
        args:
          - localhost.yml
        additional_dependencies:
          # https://github.com/kellyjonbrazil/jc/releases
          - jc==1.25.3
          # https://github.com/jmespath/jmespath.py/tags
          - jmespath==1.0.1
...
```

```bash
pre-commit run --all
Ansible Lint.............................................................Passed
```
