### ISSUE TITLE
Tag skip_ansible_lint doesn't work for [E204] Lines should be no longer than 120 chars

### ISSUE THREAD

**Issue by wildermesser** [ansible/ansible-lint#451]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version 
ansible 2.7.5
ansible-lint --version
ansible-lint 4.0.0
```

- ansible installation method: OS package
- ansible-lint installation method: OS package

# Desired Behaviour
Tag `skip_ansible_lint` should disable all rules check for task

# Actual Behaviour (Bug report only)

Tag `skip_ansible_lint` doesn't skip `[E204] Lines should be no longer than 120 chars`
Теst playbook
```
- name: Test long string
  hosts: all
  tasks:
    - name: Command
      command: wget https://very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.long.string.very.very.long.string
      tags:
        - skip_ansible_lint
```
OUTPUT:
Examining linttest.yml of type playbook
linttest.yml:6: [E204] Lines should be no longer than 120 chars

So, `[E303] wget used in place of get_url or uri module` is skipped, but [E204] doesn't.
