### ISSUE TITLE
Unrecognized type <<class 'ansible.template.native_helpers.AnsibleUndefined'>>

### ISSUE THREAD

**Issue by mooky31** [ansible/ansible-lint#4579]
##### Summary

Exception with ipaddr filter

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

Ansible EE based on RHEL-ubi9-minimal

```
ansible-core              2.18.4
ansible-lint              25.2.1
```

##### STEPS TO REPRODUCE

Trying to lint `{{ item.subnet | ansible.utils.ipaddr('network') }}` leads to `jinja[invalid]: An unhandled exception occurred while templating '{{ item.subnet | ansible.utils.ipaddr('network') }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Unrecognized type <<class 'ansible.template.native_helpers.AnsibleUndefined'>> for ipaddr filter <value>
`
##### Desired Behavior
Lint OK since there is no error

##### Actual Behavior

Playbook:
```
---
- name: Test lint
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Test lint
      ansible.builtin.debug:
        msg: "{{ ip }}"
      vars:
        ip: "{{ item.subnet | ansible.utils.ipaddr('network') }}"
      loop:
        - name: azerty
          subnet: 1.2.3.4/24
```

Lint:
```
jinja[invalid]: An unhandled exception occurred while templating '{{ item.subnet | ansible.utils.ipaddr('network') }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Unrecognized type <<class 'ansible.template.native_helpers.AnsibleUndefined'>> for ipaddr filter <value>
play-test_lint.yml:9 Task/Handler: Test lint
```
