### ISSUE TITLE
bug in rule 206 (Variables should have spaces before and after)

### ISSUE THREAD

**Issue by infothrill** [ansible/ansible-lint#498]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version
ansible 2.7.9
  config file = None
  configured module search path = [u'/home/infothrill/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/infothrill/src/git/ansible-role-hd_idle/.tox/ansible27/lib/python2.7/site-packages/ansible
  executable location = /home/infothrill/src/git/ansible-role-hd_idle/.tox/ansible27/bin/ansible
  python version = 2.7.16 (default, Mar  4 2019, 09:01:38) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]

ansible-lint --version

ansible-lint 4.1.0
```

- ansible installation method: source (via tox)
- ansible-lint installation method: source (via tox)

# Desired Behaviour

Ansible-lint should not raise error `[206] Variables should have spaces before and after: {{ var_name }}`

# Actual Behaviour (Bug report only)

Running ansible-lint 4.1.0 on a minimal playbook containing only:
```
---
- name: "Ansible-lint bug in rule 206"
  get_url:
    url: "{{ url }}"
    dest: "{{ compile_dir }}/pkg-{{ version }}.tgz"
    checksum: "{{ checksum }}"
```
Results in:

```
[206] Variables should have spaces before and after: {{ var_name }}
bug.yml:5
    dest: "{{ compile_dir }}/pkg-{{ version }}.tgz"
```
This does not seem correct, as both variables have spaces around them.
