### ISSUE TITLE
#noqa does not work on pre_tasks and post_tasks

### ISSUE THREAD

**Issue by FanchTheSystem** [ansible/ansible-lint#516]
ansible-lint 4.1.0

Example playbook.yml:
```
---
- name: hello
  hosts: all
  pre_tasks:
    - name: Get Status # noqa 303 305
      shell: 'systemctl -l status'
      changed_when: false
  tasks:
    - name: Get Status # noqa 303 305
      shell: 'systemctl -l status'
      changed_when: false
  post_tasks:
    - name: Get Status # noqa 303 305
      shell: 'systemctl -l status'
      changed_when: false
```
Current output:
```
303] systemctl used in place of systemd module
playbook.yml:5
Task/Handler: Get Status

[305] Use shell only when shell functionality is required
playbook.yml:5
Task/Handler: Get Status

[303] systemctl used in place of systemd module
playbook.yml:13
Task/Handler: Get Status

[305] Use shell only when shell functionality is required
playbook.yml:13
Task/Handler: Get Status
```

Should not output anything ...

Maybe related to https://github.com/ansible/ansible-lint/issues/484
