### ISSUE TITLE
ansible-lint erroneously detects pipes in shell when that is template

### ISSUE THREAD

**Issue by ignatenkobrain** [ansible/ansible-lint#544]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
⋊> ~/P/g/ansible on master ◦ ansible --version                                                                                                                              13:30:37
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/brain/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4rc2 (default, Jul  3 2019, 01:30:40) [GCC 9.1.1 20190605 (Red Hat 9.1.1-2)]
⋊> ~/P/g/ansible on master ◦ ansible-lint --version                                                                                                                         13:30:54
ansible-lint 4.1.0
```

- ansible installation method: OS package
- ansible-lint installation method: OS package

# Desired Behaviour

ansible-lint should not find this false positive…

# Actual Behaviour (Bug report only)

```yaml
---
- name: Test
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Test
    shell: echo
      {% for i in range(nameservers | length) %}
      {{ nameservers[i] }}
      {% endfor %}
    changed_when: false
  vars:
    nameservers:
    - 8.8.8.8
    - 4.4.4.4
```

And ansible-lint returns:

```
[306] Shells that use pipes should set the pipefail option
test.yml:6
Task/Handler: Test
```

I did not check code, but I think it just checks whether pipe is present in shell string, but shell is actually jinja2 template, so in this case it is false-positive.
