### ISSUE TITLE
Inconsistent test with pre-commit

### ISSUE THREAD

**Issue by jedla01** [ansible/ansible-lint#632]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.8.5.post0
  config file = None
  configured module search path = ['/Users/pjedlicka/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pjedlicka/ansible-dev/ansible/lib/ansible
  executable location = /Users/pjedlicka/ansible-dev/ansible/bin/ansible
  python version = 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

ansible-lint 4.1.1a0
```

- ansible installation method: source
- ansible-lint installation method: pip

# Desired Behaviour

While developing an ansible role, where root of repository is the root of a role, having set no ansible-lint rules executions nor custom rules, the output from `ansible-lint .` and `pre-commit run --all-files` should be same or results from from should be at least subset of errors found to the other test. (As running `ansible-lint` is not run against tests folder).

# Actual Behaviour (Bug report only)

When running `ansible-lint .` in to role folder I am getting errors in tasks, mostly 305 Use shell only when shell functionality is required. While running `pre-commit run --all-files` or run on the file directly founds no errors at all.
Pre-commit config:
```
---
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.1.1a0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
```

- Ansible-lint output:
```
roles/abc$ ansible-lint .
[305] Use shell only when shell functionality is required
roles/abc/tasks/main.yml:4
```
- Pre-commit output:
pre-commit run --files tasks/main.yml
Ansible-lint.............................................................Passed
