### ISSUE TITLE
ansible-lint not working with pre-commit

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible-lint#649]
# Issue Type
- update the documentation

# Ansible and Ansible Lint details

```
ansible --version                                                                                                                                                                                                      
ansible 2.9.2
  config file = /Users/nicolasg/.ansible.cfg
  configured module search path = ['/Users/nicolasg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nicolasg/venv/ansible2.9/lib/python3.7/site-packages/ansible
  executable location = /Users/nicolasg/venv/ansible2.9/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]

ansible-lint --version
ansible-lint 4.2.0

```

- ansible installation method pip
- ansible-lint installation method:  pip

I have the bellow playbook which I'm trying to test Trailing whitespace on purpose, if I run ansible-lint manually I do get the right errors but my pre-commit it is showing as **Passed** ...
 
### test.yml    : 
```                                                                                                                                                                                                        
- hosts: test
  roles:
    - { role : test, tags: [ 'test-role' ] }



```

# Desired Behaviour
```
ansible-lint test.yml -v                                                                                                                                                                                               
Examining test.yml of type playbook
[201] Trailing whitespace
test.yml:2
  roles:

[201] Trailing whitespace
test.yml:3
    - { role : test, tags: [ 'test-role' ] }

```

# Actual Behaviour
### .pre-commit-config.yaml 
```
repos:
-   repo: https://github.com/ansible/ansible-lint.git
    rev: v4.2.0
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
```
```
pre-commit install                            
pre-commit installed at .git/hooks/pre-commit

git add test.yml 

git status                                                                                                                                                                                            
On branch test-pre-commit
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   test.yml

git commit -m 'test'                                                                                                                                                                                                  
Ansible-lint.............................................................Passed
[ng-test-git-hook a85f31f] test
 1 file changed, 6 insertions(+)
 create mode 100644 test.yml
```

**Comment by webknjaz** [comment]
@ssbarnea ^

**Comment by ssbarnea** [comment]
I suspect this is caused by older way to call ansible-lint, the one passing each file, which prevents it from using the detection logic.

The newer way to configure the pre-commit looks like https://github.com/openstack/tripleo-ci/blob/master/.pre-commit-config.yaml#L24-L34 and I suppose it would work fine.

@nicolas-g Please try to use model above and see if that gives you desired results. If true we can rephrase the bug report to update the documentation about how to setup the hook.

Also keep in mind that unless you use the newer model linter will scan only modified files, not all files in the repository, which may explain your error. In that case, we should close it as a not-a-bug.

**Comment by nicolas-g** [comment]
@ssbarnea thanks for the reply, I didn't test new config you posted above but it seems that by just simply adding  `entry: ansible-lint` in my config it makes it work.

> Also keep in mind that unless you use the newer model linter will scan only modified files, not all files in the repository, which may explain your error.

I'm aware of that I did many tests to confirm this is not the case.

**Comment by trevorrea** [comment]
If it helps I've been setting up pre-commit today for an Ansible repo and used this configuration based on the sample configuration provided and the new pre-commit configuration format

```
- repo: local
  hooks:
    - id: ansible-lint
      name: Ansible-lint
      description: This hook runs ansible-lint.
      entry: ansible-lint --force-color .
      language: python
      # do not pass files to ansible-lint, see:
      # https://github.com/ansible/ansible-lint/issues/611
      pass_filenames: false
      always_run: true
```

**Comment by webknjaz** [comment]
I believe that it's now fixed on master https://github.com/ansible/ansible-lint/blob/19986b4/.pre-commit-hooks.yaml#L9.

**Comment by m-khvoinitsky** [comment]
It's not fixed. `entry` in `.pre-commit-hooks.yaml` should not contain dot as a positional argument because `ansible-lint` treats it as a role directory, doesn't find role there and silently does nothing. Instead, it sould not contain positional arguments at all — in this case `ansible-lint` recursively searches for roles and playbook starting from repo root.

**Comment by papanito** [comment]
I still face this issued, despite looking trough all the comments and references issues. Here is my config

```yaml
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.7
    hooks:
      - id: ansible-lint
        always_run: true
        pass_filenames: false
        exclude_types: [markdown, shell]
        # do not add file filters here as ansible-lint does not give reliable
        # results when called with individual files.
        # https://github.com/ansible/ansible-lint/issues/611
        type: yaml
        verbose: true
        entry: ansible-lint . --force-color -p -v
        files: ^.ansible/
```

If I run `pre-commit run --all-files` the `ansible-lint` is considered `PASSED` but when I run `ansible-lint **/*.yml` I get

```bash
WARNING  Listing 1 violation(s) that are fatal
[502] All tasks should be named
roles/packages/tasks/packages_pip.yml:1
Task/Handler: pip name={{ pip_package }} __line__=2 __file__=/home/papanito/Workspaces/devenv/roles/packages/tasks/packages_pip.yml
```
