### ISSUE TITLE
'skip_ansible_lint' tag does not work with E204 (over 160 char) rules.

### ISSUE THREAD

**Issue by cahlchang** [ansible/ansible-lint#805]
##### Summary

'skip_ansible_lint' tag does not work with E204 (over 160 char) rules.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)

$ ansible --version
ansible 2.9.9
  config file = None
  configured module search path = ['/Users/myname/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/myname/.pyenv/versions/3.8.2/lib/python3.8/site-packages/ansible
  executable location = /Users/myname/.pyenv/versions/3.8.2/bin/ansible
  python version = 3.8.2 (default, May 20 2020, 17:00:00) [Clang 10.0.1 (clang-1001.0.46.4)]

$ ansible-lint --version
ansible-lint 4.2.0

```

- ansible installation method: one of source, pip, OS package
pyenv/pip
- ansible-lint installation method: one of source, pip, OS package
pyenv/pip

##### OS / ENVIRONMENT

macOS mojava

##### STEPS TO REPRODUCE

You can test with this playbook.
```yaml
- name: over 160 char (only this error is not skipped)
  set_fact:
    test: "randomstringover160char.anmtgxxp7t25mumrrkz9en42zjr3kuhkhut68ddtuya7mktagjwxzn7mts3idz2id3uyubg6ef9wxzy2g5byh2rpmj8uh8nxd949s8nwj5e323cmk5dhbyimi87b4p8k5xpihfnfa6pxj9zassx2gxei2nrextht66esgn4b"
  tags:
  - skip_ansible_lint

- set_fact: # This error will be skipped
    test2: "randomstring"
  tags:
  - skip_ansible_lint

- name: skip test
  command: whoami
  tags:
  - skip_ansible_lint
```

```console
$ ansible-lint -p *.yml
roles/test_role/tasks/main.yml:3: [E204] Lines should be no longer than 160 chars
```

##### Actual Behaviour

skip_ansible_lint should be available for all rules.

**Comment by ssbarnea** [comment]
I think that his is likely to never work because that check comes far before we even load the tasks, so we have no knowledge that the offending line is even part of a task. Use inline noqa to bypass it.

I am even considering proposing a deprecation use of `skip_ansible_lint` as it too generic and limited.

**Comment by cahlchang** [comment]
So that's it.
Certainly noqa seems to work for this pattern.

```yaml
- name: over 160 char (only this error is not skipped)
  set_fact:
    test: "randomstringover160char.anmtgxxp7t25mumrrkz9en42zjr3kuhkhut68ddtuya7mktagjwxzn7mts3idz2id3uyubg6ef9wxzy2g5byh2rpmj8uh8nxd949s8nwj5e323cmk5dhbyimi87b4p8k5xpihfnfa6pxj9zassx2gxei2nrextht66esgn4b" # noqa 204
```

```console
$ ansible-lint -p *.yml
$ # no output
```

Thank you for teaching me.
I also agree to deprecate the `skip_ansible_lint` tag.
