### ISSUE TITLE
Ansible Lint reports git missing version

### ISSUE THREAD

**Issue by monorailpilot** [ansible/ansible-lint#906]
# Issue Type
- Bug report

# Ansible and Ansible Lint details
ansible 2.8.2
ansible-lint 4.2.0

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

The git module can be used to simply pull the hash of the code checked out, for example:
```yaml
  - name: "Get post deploy code release hash"
    git:
      repo: "."
      dest: "."
      clone: no
      update: no
    connection: "local"
    become: false
    register: git_commit
```
This should not report an error in ansible-lint

# Actual Behaviour (Bug report only)

ansible lint is reporting an error
[401] Git checkouts must contain explicit version
*FILE LOCATION HIDDEN*
Task/Handler: Get post deploy code release hash
